CREATE TABLE IF NOT EXISTS Base_Consolidada_Asistentes_Catman (
    `Nombre` VARCHAR(53) CHARACTER SET utf8,
    `email` VARCHAR(69) CHARACTER SET utf8
);
INSERT INTO clientes VALUES
    ('Alexandra Niño Manrique','Alexandracomunicacion@Gmail.Com'),
    ('Andres Hernandez','Andres.Hernandez@Dunnhumby.Com'),
    ('Angela Villegas','Angela.Villegas@Totalmarketingsupport.Com'),
    ('Angie Rios','Angie.Rios@Unilever.Com'),
    ('Conf #13 Catalina Isaza (Catalina Isaza Molina)','Catalina.Isazamolina@Dunnhumby.Com'),
    ('Génesis Aleman','Cenyakce@Hotmail.Com'),
    ('Zoom','Contacto@Dgonlucesysonido.Com'),
    ('Diana Castano','Di.Macara@Icloud.Com'),
    ('Diana Delgado','Diana.Delgado@Grupobimbo.Com'),
    ('Tatiana Cadena','Digital@V2Vcolombia.Com'),
    ('Domenico Barbato','Domenico.Barbato@Juanvaldezcafe.Com'),
    ('Enrique Cabrera','Enrique@Whcolombia.Com'),
    ('Erika Perez','Erika.Perez@Ferrero.Com'),
    ('Viviana Gomez','Ferchita23@Yahoo.Com'),
    ('Gabriel Richaud','Gabriel@Iabmexico.Com'),
    ('Beatriz Calero','Gerenciaventas@Beisbol.Com.Co'),
    ('Iveth Vengoechea','Ivethv@Sempertex.Com'),
    ('Ivette Ortiz Navarrete','Ivetteortiz@Mitzu.Com'),
    ('Johny Ariza','J.Ariza@Bullmarketing.Com.Co'),
    ('Jasseth Diaz','Jasseth.Diaz@Gmail.Com'),
    ('Juan Cardenas','Jcardenas@Gpricecorp.Com'),
    ('Julian Clavijo','Jclavijo@Insitel.Com'),
    ('Jessica Castaño','Jesicasta@Hotmail.Com'),
    ('Juliana Morales','Jmorales@Comercialnutresa.Com.Co'),
    ('Johanna Marcela Barrera Chavez','Johanna.Barrera@Papeles.Com'),
    ('Conf#3 Juan Caro Caro','Juan.Caro@Kantar.Com'),
    ('Juan Sebastian Montes','Juan.Montes@Dunnhumby.Com'),
    ('Julián Argüello (Julián Forero)','Julian.Arguello@Guest.Ferrero.Com'),
    ('Kathy Ydrovo','Kathy@Kolvoz.Com'),
    ('Laura R','Laura.Robayo@Loreal.Com'),
    ('Liliana Merchan','Liliana.Merchan@Brinsa.Com.Co'),
    ('Lina Vanegas','Lina.Vanegas@Unilever.Com'),
    ('Marco Echeverry','Ma.Echeverry@Hv.Com.Co'),
    ('Margarita Arango','Margarita_Arango@Colpal.Com'),
    ('Mauricio Quintero','Mauricio.Quintero@Grupobimbo.Com'),
    ('Mariana Tapia Zambrano','Mdtapia@Comercialnutresa.Com.Co'),
    ('Marcela Echeverri Rodríguez','Mecheverri@Novaventa.Com'),
    ('Maria Pelaez','Mercadeo@Demetalicos.Com'),
    ('Paola Mejia','Mp.Mejia@Hv.Com.Co'),
    ('Nicolás Barbosa','Nicolas.Barbosa@Unilever.Com'),
    ('G O','Ochoa@Rocketmail.Com'),
    ('Olivia Gonzalez','Olivia@Tucash.Co'),
    ('Oscar Trujillo','Oscartrujillo@Unidrogas.Com.Co'),
    ('Paula Alzate','Paalzate@Comercialnutresa.Com.Co'),
    ('Paolar','Paola.Rubiano@Dunnhumby.Com'),
    ('Santiago Armel','Sarmel@Novaventa.Com'),
    ('Natalia Quenguan','Seahorsecolombia@Gmail.Com'),
    ('Susana Maya','Smmaya@Comercialnutresa.Com.Co'),
    ('Valentin Alvarado B. (Valentin Benitez)','Valentin.Alvarado92@Outlook.Es'),
    ('Conf#10 Veronica Pachon (Veronica Pachon Latorre)','Veronica.Pachonlatorre@Nielseniq.Com'),
    ('William Farah','Wfarah@Venturasfoodsa.Com'),
    ('Nicolas Guzman','Christian.N.Guzman@Gsk.Com'),
    ('Miguel Angel Feria','Miguelaf@Yupi.Com.Co'),
    ('Andrés Mauricio Palacio Montaño','Am.Palacio@Adateceu.Com'),
    ('Alejandra Puerta Alvarez','Apuerta@Casaluker.Com.Co'),
    ('Carlos Mejia','Ca.Mejia@Hv.Com.Co'),
    ('Cesar Varela','Cesar.Varela@Unilever.Com'),
    ('Camila Restrepo','Crestrepo@Comercialnutresa.Com.Co'),
    ('Diana Tasama','Diana.Tasama@Babaria-Int.Com'),
    ('Diego Cely','Diego.Celysarmiento@Gmail.Com'),
    ('Laura Leãƒâ³N Torres','Laura.Leon9@Gmail.Com'),
    ('Jaime García','Jaime.Garcia@2Brothers.Co'),
    ('Maria Clara Londoño ','Mclondono@Mmm.Com'),
    ('Daniela Duarte Arboleda','Dduarte@Mmm.Com'),
    ('Katherine Ydrovo','Kydrovo@Hotmail.Com'),
    ('Natalia Pulido','Natypu@Hotmail.Com'),
    ('Yesenia Reyes','Aaahousewares@Gmail.Com'),
    ('Patrick Loyer','Patrick.Loyer@Ab-Inbev.Com'),
    ('Evelyn Velásquez','Evelyn.Velasquezdelgado@Ab-Inbev.Com'),
    ('Luz Adriana Girado ','Adriana.Giraldo20@Gamil.Com'),
    ('Viviana  Libreros ','Viviana.Libreros@Abbott.Com'),
    ('Paola Moreno','Yepamoga@Hotmail.Com'),
    ('Mario Andres Uran Martinez','Mario.Uran@Abbott.Com'),
    ('Andrea Velez','Andrea.Velezgiraldo@Abbott.Com'),
    ('Fabian  Ochoa ','Fagiea@Gmail.Com'),
    ('Diana C. Reyes  Goyeneche','Diana.Reyes1@Abbott.Com'),
    ('Maria Paula Gomez ','Mariapaula.Gomez@Abbott.Com'),
    ('Edgar Ulises Hernandez Lara','Ulisesh6@Hotmail.Com'),
    ('Daniel  Bustamante ','Daniel.Bustamante@Abbott.Com'),
    ('Allison  Salebe Cabrales','Allison.Salebe@Abbott.Com'),
    ('Lucia Amaya','Lucia.Amaya@Abbott.Com'),
    ('Reynaldo Antonio Foschini Viloria','Antonio.Foschini@Abbott.Com'),
    ('Angela Cardenas','Angela.Cardenas@Abbott.Com'),
    (' Juan Ricardo Pelaez','Juanricardopelaez@Hotmail.Com'),
    ('Stella Torres','Stella.Torres@Abbott.Com'),
    ('Felipe  Gutierrez Camacho','Felipe.Gutierrez@Abbott.Com'),
    ('Wilson  Bedoya Castañeda','Wilson.Bedoya@Abbott.Com'),
    ('Sergio Alejandro Alvarado Sales','Sergio.Alvarado995@Gmail.Com'),
    ('Sandra Galvis','Sandra.Galvis@Abbott.Com'),
    ('Andrea  Baez ','Andrea.Baez@Abbott.Com'),
    ('Sebastian  Aristizabal ','Sebastian.Aristizabal@Abbott.Com'),
    ('Alexander  Perilla ','Alexander.Perillasanchez@Abbott.Com'),
    ('Adriana  Gonzalez ','Adriana.M.Gonzalez@Abbvie.Com'),
    ('Monica  Lesmes Palacio','Monica.Lesmespalacio@Abbvie.Com'),
    ('Lucí Vergara','Lucia.Vergara@Ab-Inbev.Com'),
    ('Julieth Mayorga','P-Comunicaciones@Accionplus.Com'),
    ('Milena Serrano','Medios-Digitales@Accionplus.Com'),
    (' Juan Pablo Hernández ','Juan.P.Hernandez@Nielsen.Com'),
    ('Catalina Andrea Ramirez Benitez','Catalina.Ramirez@Nielsen.Com'),
    ('Roberto Garcia','Roberto.Garcia@Nielsen.Com'),
    ('Carolina Vargas','Carolina.Vargas@Nielsen.Com'),
    ('Maria Alejandra Osorio / Maria Paula Marin','Alejandra.Osorio@Acopibogota.Org.Co'),
    ('Cesar Naranjo ','Cesar@Acronia.Com.Co'),
    ('Carolina Castillo ','Carocastillomon@Gmail.Com'),
    ('Andres Correa Mongui','Andres.Correa@Adareinternational.Com'),
    ('Esperanza Espitia ','Esperanza.Espitia@Adareinternational.Com'),
    (NULL,'Adiquim@Hotmail.Com'),
    (NULL,'Notificacionessaf@Falabella.Com.Co'),
    (NULL,'Agricol@Agricolacolombiana.Com'),
    ('Yusbany Alejandra Ospina Henao','Alejandra.Ospina@Agricolahimalaya.Com'),
    ('Claudia Yaneth Alarcon Saiz','Claudia.Alarcon@Tehindu.Com'),
    ('Andres Rubio','Trade.Marketing@Arrozsonora.Com.Co'),
    ('Astrid Restrepo','Astrid.Restrepo@Arrozsonora.Com.Co'),
    ('Luis Gordillo','Luis.Gordillo@Arrozsonora.Com.Co'),
    ('Luz Miryan Castellanos','Luz_Castellanos@Br.Ajinomoto.Com'),
    ('Luis Enrique Duarte Chavez','Luis.Duarte_Chavez@Alcon.Com'),
    ('Sandra Liliana Ramos Pinzon','Sandra.Ramos_Pinzon@Alcon.Com'),
    ('Felipe Jimenez','Mercadeo_Dg@Aldiaferreteria.Com'),
    ('Andres Nuñez','Andres.Nunez@Aldoronline.Com'),
    ('Ivette Godinez','Ivette.Godinez@Alen.Com.Mx'),
    ('María Gabriela Barrera Arevalo','Mgba4694@Gmail.Com'),
    ('Diego Javier Medina Forero','Diego.Medina@Algamar.Com.Co'),
    ('Sergio Andrés Medina Meneses','Mercadeo@Algamar.Com.Co'),
    ('Monica Perez','Monica.Perez@Alianzafarmaceutica.Com'),
    ('Juan Carlos Salazar','Juan.Salazar@Alianzateam.Com'),
    ('Isabel Leo','Cleog@Alicorp.Com.Ec'),
    ('Maria Teresa Restrepo ','Mrestrepo@Aimentoscarnicos.Com.Co'),
    ('Shirley Castro','Smcastro@Alimentoscarnicos.Com.Co'),
    ('Andres Leonardo Solano','Alsolano@Alimentoscarnicos.Com.Co'),
    ('Ernesto Quiroga Gutierrez','Jquiroga@Alimentoscarnicos.Com.Co'),
    ('Juan Manuel Rodriguez Manzano ','Jmrodriguez@Alimentoscarnicos.Com.Co'),
    (NULL,'Vgramirez@Alimentoscarnicos.Com.Co'),
    ('Jose Acosta ','Jacosta@Alimentosdecalidad.Co'),
    ('Paula Villalba','Paula.Villalba@Empresas-Polar.Com'),
    ('Marcelo Cucalón','Analistaautomatizacion@Yupi.Com.Co'),
    ('Carolina Martinez','Martinez_Carolina@Allergan.Com'),
    (NULL,'Felipeospinacaballero@Grupo-Exito.Com'),
    (NULL,'Recepcionppal@Almacenesparaiso.Com'),
    ('Daniela Florez','Daniela.Florez@Alpha245.Com'),
    ('Gabriela Guerrero Figueroa ','Gabriela.Guerrero@Alpina.Com'),
    ('Natalia Alonso ','Natali.Alonso@Alpina.Com'),
    ('Diana','Dcgoyeneche@Gmail.Com'),
    ('Julian David Hernandez Baez','Julian.Hernandez@Alpina.Com'),
    ('Andrea Acosta Vega','Andrea.Acosta@Alpina.Com'),
    ('Natalia Alonso','Natalia.Alonso@Alpina.Com'),
    ('Juliãƒâ¡N Suãƒâ¡Rez Puerta','Juliansuarezp@Gmail.Com'),
    ('Nicolas Forero','Nicolas.Forero@Alpina.Com'),
    ('Claudia  Giraldo ','Claudia_Giraldo@Eficacia.Com.Co'),
    ('Ricardo  Benitez ','Ricardo_Benitez@Eficacia.Com.Co'),
    ('Esteban Ocampo','Esteban.Ocampo@Alpina.Com'),
    ('Paola Ines Cruz Carvajal ','Paola.Cruz@Alpina.Com'),
    ('Karen Bautista','Karen.Bautista@Alpina.Com'),
    ('Vanessa Beltrán Pinilla','Vanessa.Beltran@Alpina.Com'),
    ('Laura Cespedes','Lauraa.Cespedes@Alpina.Com'),
    (NULL,'Rarango@Alpina.Com.Co'),
    ('Nidia  ','Ngutierrez@Alpura.Com'),
    ('Laura Lãƒâ³Pez ','Lalopezr@Alqueria.Com.Co'),
    ('Diana Perez','Dperez@Alqueria.Com.Co'),
    ('Jairo Dorado ','Jdorado@Alqueria.Com.Co'),
    ('Andres Yepes ','Ayepes@Alqueria.Com.Co'),
    ('Nataly Barrera','Nbarrera@Alqueria.Com.Co'),
    ('Juanita Sanchez','Jmsanchezp@Alqueria.Com.Co'),
    ('Maria Alejandra Suarez Ibarra','Masuarez@Alqueria.Com.Co'),
    ('William Mora ','Wmora@Alqueria.Com.Co'),
    ('Lady Suárez ','Lady.Suarez@Altipal.Com.Co'),
    (' Nadia Arce','Andrea.Cortes@Altipal.Com.Co'),
    ('Ana Maria Jaramillo ','Ana.Jaramillo@Altipal.Com.Co'),
    ('Laura Nataly Herrera González','Laura.Herrera@Altipal.Com.Co'),
    ('Juan Carlos Gómez','Jccadena@Amazon.Com'),
    (NULL,'Ccontactenos@Americasbps.Com'),
    ('Sebastian  Daraviña ','Sdaravin@Amgen.Com'),
    ('Natalia Andrea Paez Peñaloza','Npaez@Amgen.Com'),
    ('David Burgos','David.Burgos@Antillana.Com.Co'),
    (NULL,'Aronagrupoe.Sa@Gmail.Com'),
    ('Manuel Caicedo Suso','Gerentemercadeo@Blanquita.Com.Co'),
    (NULL,'Andrea.Monsalve@Dianacorporacion.Co'),
    ('Ignacio Gomez Escobar','Igomeze@Colombiaretail.Com'),
    ('Rodrigo  Pavez ','Rodrigo.Pavez@Astellas.Com'),
    ('Silvia  Gimenez ','Silvia.Gimenez@Astellas.Com'),
    ('Oscar  Gomez Rodriguez','Oscar.Gomez@Astellas.Com'),
    ('Paola  Idarraga ','Paola.Idarraga@Astellas.Com'),
    ('Oscar  Cañon ','Oscar.Canon@Astellas.Com'),
    ('Jacqueline  Arellano ','Jacqueline.Arellano@Astellas.Com'),
    ('Mauricio  Henao Chacón','Mauricio.Henao@Astellas.Com'),
    ('Miguel  Cristancho Martinez','Miguel.Cristancho@Astellas.Com'),
    ('Iván  Peñuela ','Ivan.Penuela@Astellas.Com'),
    ('Julián  Esponda ','Julian.Esponda@Astellas.Com'),
    ('Maria Fernanda Silva ','Maria.Silva@1Astrazeneca.Com'),
    ('Camilo  Arroyave ','Camilo.Arroyave@Astrazeneca.Com'),
    ('Camilo Alberto Plazas Zarate','Camilo.Plazas@Audifarma.Com.Co'),
    ('Johana Martínez','Marilyn.Martinez@Audifarma.Com.Co'),
    ('Camila  Bermudez ','Maria.Bermudez@Audifarma.Com.Co'),
    ('Maria Alejandra Alonso V','Alejandra.Alonso@Aurobindo.Com'),
    ('Kamlesh  Thakkar ','Kamlesh.Thakkar@Aurobindo.Com'),
    ('Diego  Osorio','Dosorio09@Hotmail.Com'),
    ('Newar  Giraldo ','Newargiraldo1981@Gmail.Com'),
    ('Eduardo Medina','E.Medina@Avgust.Com.Co'),
    ('Alcira Romero','Alcira.Romero@Avianca.Com'),
    ('Gonzalo Monroy Tovar','Gonzalo.Monroy@Avicolaelmadrono.Com'),
    ('Marco  Gonzalez ','Marco.Gonzalez@Axiomalogicdata.Com'),
    ('Felipe  Camacho ','Felipe.Camacho@Yahoo.Com'),
    ('Maria Alejandra Viãƒâ±As ','Marialewood@Hotmail.Com'),
    ('Carolina Plaza Jimenez','Carolina.Plaza@Azulk.Com'),
    ('Janeth Valencia Otero','Janeth.Valencia@Azulk.Com'),
    ('Gloria Esperanza Roncancio Roncancio','Gloria.Roncancio@Azulk.Com'),
    ('Stefano Valdettaro','Stefano.Valdettaro@Ab-Inbev.Com'),
    ('Diego Pinto','Diego.Pinto@Ab-Inbev.Com'),
    ('Marcia Estrada','Marcia.Estrada@Backus.Sabmiller.Com'),
    ('Alexandra Noriega','Alexandra.Noriega@Ab-Inbev.Com'),
    ('Diana Marcela  Chaparro','Dchaparro@Fundaciongruposocial.Co'),
    ('Carolina  Bernal','Cbernal@Fundaciongruposocial.Co'),
    ('Paola Vargas Jurado','Yvargasj@Davivienda.Com'),
    ('Sandra Yaneth González / Freddy Oswaldo Arévalo Reyes','Sgonzalez@Bancodeoccidente.Com.Co  / Farevalo@Bancodeoccidente.Com.Co'),
    ('Sebastian Sanchez  ','Sebsanch@Bancolombia.Com.Co'),
    ('Fernando  Robledo ','Fernandor@Banmedica.Com.Co'),
    ('Sara Basto','Sara_Gabriela__Basto_Barrera@Bat.Com'),
    ('Diana Gonzalez','Diana.Gonzalez2@Co.Ab-Inbev.Com'),
    ('Natalia Rangel','Nataliarangel.R16@Gmail.Com'),
    ('Carolina Gutierrez','Cgutierrez@Bogotabeercompany.Com'),
    ('Betty  Garcia ','Bgarcia@Bogotabeercompnay.Com'),
    ('Martha Baron','Martha_Baron@Baxter.Com'),
    ('María Camila Ballen ','Mariacamila.Ballen@Bayer.Com'),
    ('Daniel  Cuervo Estrada','Daniel.Cuervo@Bayer.Com'),
    ('Nicolas Esteban Saade Rivera','Nicolasesteban.Saade@Bayer.Com'),
    ('Santiago  Scarpetta O','Carlossantiago.Scarpetta@Bayer.Com'),
    ('Andrea  Moreno ','Andrea.Moreno@Bayer.Com'),
    ('Liliana Pava Ovalle ','Liliana.Pava@Bayer.Com'),
    ('Andrea Johanna Hernandez Nieto','Andrea.Hernandez@Bayer.Com'),
    ('Lina Maria Palau ','Linamaria.Palau@Bayer.Com'),
    ('Juan Camilo Rojas Mantilla','Juancamilo.Rojas@Bayer.Com'),
    ('Maria Del Rosario Lock ','Maria.Lock@Bayer.Com'),
    ('Maria Del Pilar','Mariadelpilar.Dominguez@Bayer.Com'),
    ('Andrés  Flautero Parra','Andres.Flautero@Bayer.Com'),
    ('Henry David Forero Bejarano','Henry_Forero@Bcnmedical.Com'),
    ('Fernando España','Hablemos@Be2Eat.Com'),
    ('Diana Garcia','Diana.Garcia@Beiersdorf.Com'),
    ('Lady Morales','Lady.Morales@Beierddof.Com'),
    ('Nelson Mosquera Diaz ','Nelsonmosquera@Beisbol.Com.Co'),
    ('Angela Bernal ','Angela.Bernal@Bellapiel.Com.Co'),
    ('Carolina Gutierrez ','Carolina.Gutierrez@Bellapiel.Com.Co'),
    ('Nicolas Caceres ','Nicolas.Caceres@Bellapiel.Com.Co'),
    ('Angela Bernal  ','Angela.Bernal@Bellaiel.Com.Co'),
    ('Natalia Andrea Leal Tascãƒâ³N','Nlealtascon@Gmail.Com'),
    ('Juan Pinto','Jmpinto@Sadinsa.Com'),
    ('Javier Bautista ','Gerencia@Bigmedical.Co'),
    ('Daniela Zabala','Laura.Zabala01@Grupobimbo.Com'),
    ('Mauricio Quintero Buitrago','Maruicio.Quintero@Grupobimbo.Com.Co'),
    ('Mónica Bejarano','Monica.Bejarano@Grupobimbo.Com'),
    (NULL,'Jose.Jaramillo@Grupobimbo.Com'),
    ('María Juliana Ortegón Chicuasuque','Maria.Ortegon@Grupobimbo.Com');
    -- Aquí vamos
INSERT INTO Base_Consolidada_Asistentes_Catman VALUES
    (NULL,'Paula.Moreno@Grupobimbo.Com'),
    ('Camilo Cortés','Camilo.Andres@Grupobimbo.Com'),
    ('Neyffi  Rodríguez ','N.Rodriguez@Biosidus.Com'),
    ('Pedro  Cadena ','P.Cadena@Biosidus.Com'),
    ('Marcelo  Mejía ','Mmejia@Biotecnik.Com'),
    ('Juan  Escallon ','Juan.Escallon@Grupobiotoscana.Com'),
    ('Jorge Medina','Jom6914@Gmail.Com'),
    ('Mayra  Bastidas ','Mayra.Bastidas@Boehringer-Ingelheim.Com'),
    ('Lady  Sánchez Trujillo','Lady.Sanchez@Boehringer-Ingelheim.Com'),
    ('Antonio  Ospina ','Antonio.Ospina@Boehringer-Ingelheim.Com'),
    ('Eddy Ortiz Suarez','Eortiz@Panisimo.Com'),
    ('Jessica Castaño Lavado','Jessica.Castano@Bredenmaster.Com'),
    ('Angela Birceño','Angelamariabriceno@Hotmail.Com'),
    ('Andrea Builes Salazar','Andrea.Builes@Brinsa.Com.Co'),
    ('Liliana Garcia Vargas','Liliana.Garcia@Brinsa.Com.Co'),
    ('Daniela Sterling Velez','Daniela.Sterling@Brinsa.Com.Co'),
    ('Jacqueline Montoya Gutierrez','Jacqueline.Montoya@Brinsa.Com,Co'),
    ('Jacqueline Montoya Gutierrez','Jacqueline.Montoya@Brinsa.Com.Co'),
    (NULL,'Santiagorivas@Brinsa.Com.Co'),
    ('Guiomar  Corrales Acevedo','Guiomar.Corrales@Essity.Com'),
    ('Natalia Giraldo','Natygh1.Ng@Gmail.Com'),
    ('Ana  Teixeira ','Ana.Teixeira@Bussie.Com.Co'),
    ('Rodrigo Antonio Perez Cruz','Rodrigo.Perez@Bussie.Com.Co'),
    ('Luisa Fernanda Restrepo ','R_Luisafernanda75@Hotmail.Com'),
    ('Dairon Stivel Cuaces Queta','Dairon.Cuaces@Labinco.Com.Co'),
    ('Marcel Ramírez','Direccion@Busymind.Co'),
    ('Fanny Martinez','Fanny.Martinez@Somoscmi.Com'),
    ('Ruth Bautista','Rbautista@Cafam.Com.Co'),
    ('Maria Alexandra Placeres','Placeres.M@Grupo-Cala.Com'),
    ('Andrea Lopez','Lopez.A@Grupo-Cala.Com'),
    ('Andres Marin','Acano@Cartama.Com'),
    ('Argenis Murcia Franco ','Amurciaf@Casaluker.Com.Co'),
    ('Alejandra Puerta ÃƒâLvarez ','Puertale@Hotmail.Com'),
    ('Nicolás Ruiz','Nruiz@Casaluker.Com.Co'),
    ('Badwin Alfonso','Balfonso@Casaluker.Com.Co'),
    ('Claudia Lasprilla','Clasprilla@Casaluker.Com.Co'),
    ('Daniela Sanchez Romero','Mdsanchez@Casaluker.Com.Co'),
    ('Gineth Espitia','Nespitia@Casaluker.Com.Co'),
    (NULL,'Aamador@Casaluker.Com.Co'),
    ('Camilo Andres Baron','Cvaron@Casaluker.Com.Co'),
    ('Jose Alejandro Londoño Bedoya','Jalondono@Casaluker.Com.Co'),
    ('Diana Marcela Enciso','Denciso@Casaluker.Com.Co'),
    ('Cristina Garizabalo','Cgarizabalo@Lukerchocolate.Com'),
    ('Alejandra Rodriguez','Mrodriguezf@Casaluker.Com.Co'),
    ('Alberto  Martinez','Atomba@Casaluker.Com.Co'),
    ('Guillermo Riaño','Griano@Casaluker.Com.Co'),
    ('Jhon Jairo Torres','Jjtorres@Casaluker.Com.Co'),
    ('Ana Isabel Valencia Fonseca','Avalencia@Casaluker.Com.Co'),
    ('Ramses Landaverde ','Ramses.Landaverde@Catmanexpert.Com'),
    ('Siomara Villalta Delgado ','Svillalta@Cuestamoras.Com'),
    ('Carolina Sepulveda Franco','Carolinasepulveda@Celema.Com.Co'),
    ('Laura Marin Tabares','Mercadeo@Celema.Com.Co'),
    ('Luis Miguel ÃƒâNgel Garcãƒâ­A ','Luchin.Angel@Hotmail.Com'),
    ('Luis Miguel ÃƒâNgel Garcãƒâ­A ','Luis.Angel@Cencosud.Com.Co'),
    (NULL,'Armando.Penaranda@Centelsa.Com.Co'),
    ('Laurie Molina','Lmolinac@Postobon.Com.Co'),
    ('Gustavo Cabrales ','Gcabrales13@Gmail.Com'),
    ('Mariangel Sifontes','Msifontesa@Gmail.Com'),
    ('Juan Camilo Londoãƒâ±O','Juancamilolc@Gmail.Com'),
    ('Álvaro Giraldo','Juliang_017@Hotmail.Com'),
    (NULL,'Eduardo.Calderon@Chrysal.Com.Co'),
    ('Angelica Larissa Romero Llamas','Larissa.Romero@Churchdwight.Com'),
    ('Juliana Bedoya Zapata','Jbedoya@Distrihogar.Com.Co'),
    ('Juliana Gutiérrez Arango','Jgutierrez@Distrihogar.Com.Co'),
    ('Paula Andrea Alzate Giraldo','Palzate@Distrihogar.Com.Co'),
    ('Alexander  Bautista ','Alexander.Bautista@Sigra.Com'),
    ('Eliana Marcela Muñoz Araujo','Eliana.Munoz@Claro.Com.Co'),
    ('Diana Alejandra Molano Franco','Diana.Molano@Claro.Com.Co'),
    ('Nidia Galeano','Nidia.Galeano@Claro.Com.Co'),
    (NULL,'Francisco.Lopez@Claro.Com.Co'),
    ('Juan Toscano','Juan.Toscano@Claro.Com.Co'),
    ('Fred Rodriguez','Freddy.Rodriguez@Claro.Com.Co'),
    ('Fernando Gustavo Rodriguez','Fernando.Rodriguezn@Claro.Com.Co'),
    ('Mauricio Caballero Osma','Mauricio.Caballero@Claro.Com.Co'),
    ('Camilo Guerrero','Camilo.Guerreror@Claro.Com.Co'),
    ('Adriana Legaspi ','Adriana.Legaspi@Clorox.Com'),
    ('Karla Palencia','Karla.Palenciao@Somoscmi.Com'),
    ('Claudia Contreras','Claudia.Contreras@Somoscmi.Com'),
    ('Ana Maria Montoya ','Anammontoya@Coca-Cola.Com'),
    ('Tiago  ','Tiaoliveira@Coca-Cola.Com'),
    ('Monica Isabel Gonzalez Meza','Mgonzalezm@Cofarma.Com'),
    ('Claudia Patricia Brito Lindarte','Cbrito@Cofarma.Com'),
    ('Fabio Andres Restrepo Salazar','Frestrepo@Cofarma.Com'),
    ('Yenny Lizeth Lopez','Yennlopc@Colsubsidio.Com'),
    ('Alexandra Salinas','Alexandrasa@Colanta.Com.Co'),
    ('Marãƒâ­A Josãƒâ© Mejãƒâ­A Maestre','Mariajosemejia8@Gmail.Com'),
    ('Erika Meisel','Emeiselp@Gmail.Com'),
    ('Nicol√°S Vilches','Nicolas_Vilches@Colpal.Com'),
    ('Paola Torres','Mayerlyt@Colmedica.Com'),
    ('Andres Triana','Andrestp@Colmedica.Com'),
    ('Angela Galeano','Angelagm@Colmedica.Com'),
    ('Lina Florian','Linaf@Colmedica.Com'),
    ('Juan José Castro Novoa','Juanc@Colmedica.Com'),
    ('Leo Congo','Lcongote@Colombiaretail.Com'),
    (NULL,'Colquesos@Colquesos.Com.Co'),
    (NULL,'Cesar.A.Pena@Kcc.Com '),
    ('Paulo Fernandez','Pfernandez@Colombina.Com'),
    ('Victoria Eugenia Muriel  Carballo','Vmuriel@Colombina.Com'),
    ('Lina Maria Jaramillo ','Lmjaramillo@Colombina.Com'),
    ('Marcela Sanchez','Msanchezp@Colombina.Com'),
    ('Marisol Calderon Silva','Mcalderon@Colombina.Com '),
    (NULL,'Mmoralesc@Colombina.Com'),
    (NULL,'Nnavarrete@Colombina.Com'),
    ('Sandra Victoria Mejia Cuartas','Smejia@Colombina.Com'),
    ('Boris Andres Vasquez Laser','Bvasquez@Colombina.Com'),
    ('Ivan Dario Meza Giraldo','Imeza@Colombina.Com'),
    ('Diana Meneses','Dmeneses@Colombina.Com'),
    ('Karen Dayana Otãƒâ¡Lora Boada ','Karen.Otalorabo@Colsubsidio.Com'),
    ('Yenny Lopez ','Yenny.Lopezc@Colsubsidio.Com'),
    ('Maria Camil Londoño Nariño','Maria.Londonona@Colsubsidio.Com'),
    ('Gina Licet Mendoza Montes','Ginamenm@Colsubsidio.Com'),
    ('Luis Fernando Castellanos Granados','Luis.Castellanos@Colsubsidio.Com'),
    ('Claudia  Herrera ','Claudia.Herrera@Colsubsidio.Com'),
    ('Juan Alexander Luz Bejarano','Juan.Luzb@Colsubsidio.Com'),
    ('Hasbleidy Ramirez','Hasbleidy.Ramirez@Colsubsidio.Com'),
    ('Paco  Lopez ','Paco.Lopez@Colsubsidio.Com'),
    ('Nubia  Solano Celis','Nubia.Solano@Colsubsidio.Com'),
    ('Yordan  Reyes ','Jordan.Reyes@Colsubsidio.Com'),
    ('Jorge  Puentes ','Jorge.Puentes@Colsubsidio.Com'),
    ('Diego  Ardila ','Diego.Ardilahe@Colsubsidio.Com'),
    ('Amparo Rocio Castro Barbosa','Amparo.Castro@Colsubsidio.Com'),
    ('Omar Durán','Omar.Duranes@Colsubsidio.Com'),
    ('Pablo Enrique Rojas ','Pablo.Rojas@Colsubsidio.Com'),
    ('Paola  Salamanca ','Jeimy.Salamanca@Colsubsidio.Com'),
    ('Luz Stella Rodriguez ','Luz.Rodriguezb@Colsubsidio.Com'),
    ('Jefferson Pinilla','Jefferson.Pinillaca@Colsubsidio.Com'),
    ('Alba Prieto ','Albamarprieto@Gmail.Com'),
    ('German Ardila ','German.Ardila@Pmi.Com'),
    (NULL,'Mercadeo@Enviacolvanes.Com.Co'),
    (NULL,'Yolima.Rojas@Dihego.Com'),
    ('Natalia Niño Ramírez','Marleny.Lizarazo@Heladospopsy.Com'),
    ('Natalia Florez Torres ','Nflorez@Comercialnutresa.Com.Co'),
    ('Olan ','Ondelahoz@Comercialnutresa.Com'),
    ('Lina Vanegas','Lvvanegas@Comercialnutresa.Com.Co'),
    ('Isabella Holguin','Iholguin@Comercialnutresa.Com.Co'),
    ('Claudia Maria Mejia Albert','Cmmejia@Comercialnutresa.Com.Co'),
    ('Javier Alexander Guerrero Mora','Jguerrero@Comercialnutresa.Com.Co'),
    ('Miguel Gabriel Gonzalez','Comercialnutresa.Com.Co'),
    ('Miguel Gabriel Gonzalez','Mggonzalez@Comercialnutresa.Com.Co'),
    ('Jorge Andrés Ortiz Laguado','Jortiz@Comercialnutresa.Com.Co'),
    ('Claudia Gomez','Cmgomez@Comercialnutresa.Com.Co'),
    ('María Alejandra Alvarez','Malvareza@Comercialnutresa.Com.Co'),
    ('Gladys Vasquez','Gvasquez@Comercialnutresa.Com.Co'),
    (NULL,'Maotalvaro@Comercialnutresa.Com.Co'),
    ('Mauricio González Soto','Mgonzalez@Comercialnutresa.Com.Co'),
    ('Mariana Tapia','Tapiazmari14@Gmail.Com'),
    ('Alejandra Velasquez','Avelasquez@Comercialnutresa.Com.Co'),
    ('Miguel Aristizábal ','Maaristizabal@Comercialnutresa.Com.Co'),
    ('Luis Miguel Gonzãƒâ¡Lez ','Pracaxcgc@Comercialnutresa.Com.Co'),
    ('Andrãƒâ©S Fernando Arbelãƒâ¡Ez Peãƒâ±Aranda ','Afarbelaez@Comercialnutresa.Com.Co'),
    ('Serafín Becerra M','Sbecerra@Comercialnutresa.Com.Co'),
    ('Tatiana Sanchez','Tatiana.Samchez@Hotmail.Com'),
    ('Tatiana Sanchez','Tatiana.Sanchez@Hotmail.Com'),
    ('Nathaly Tabbal ','Nathaly.Tabal@Aldoronline.Com'),
    ('Nathaly Tabbal','Nathaly.Tabbal@Aldoronline.Com'),
    (NULL,'M.Paredes@Comestiblesitalo.Com'),
    ('Maria Clemencia Lozano Villegas','Mlozano@Cra.Gov.Co'),
    (NULL,'Jimmy.Ardila@Pintuco.Com'),
    (NULL,'Katherineb@Yupi.Com.Co'),
    (NULL,'Jhjimenez@Chocolates.Com.Co'),
    (NULL,'Ocgiraldo@Chocolates.Com.Co'),
    (NULL,'Alondono@Chocolates.Com.Co'),
    (NULL,'Cvasquez@Chocolates.Co.Com'),
    (NULL,'Shincapie@Chocolates.Com.Co'),
    (NULL,'Gdzapata@Serviciosnutresa.Com'),
    ('Yohanna  Escobar','Ycescobarn@Compensarsalud.Com'),
    ('Camilo  Mora','Camilo.Mora@Cosmeticosbelier.Com'),
    (NULL,'Contactenos@Conalvias.Com'),
    ('Claudia Duarte','Claudia.Duarte@Congrupo.Com.Co'),
    ('Christian Marin','Christianmarinu@Gmail.Com'),
    (NULL,'Hugsaav@Gmail.Com'),
    (NULL,'Mcarmona@Qbo.Co'),
    (NULL,'Construconacero@Hotmail.Com'),
    ('Jorge Enrique Abril Nieto','Jorge.Abril56@Hotmail.Com'),
    ('Leonardo Ramirez','Ramirezninoleo@Gmail.Com'),
    ('Viviana  Molina ','Vivianamolina72@Gmail.Com'),
    (NULL,'Acabarcas@Coolechera.Com'),
    (NULL,'Gerencia@Colanta.Com.Co ; Colanta@Colanta.Com.Co'),
    (NULL,'Y.Ochoa@Coopidrogas.Com.Co'),
    ('Erika Rocío Montaño Ruiz','E.Montano@Coopidrogas.Com.Co'),
    ('Leandro Ivan Lopez Mora','L.Lopezm@Coopidrogas.Com.Co'),
    ('Diego Andres Molina Betancur','Dimolin14@Gmail.Com'),
    ('Hugo Ospina ','H.Ospina@Coopidrogas.Com.Co'),
    ('Albeiro Guzmán Palacio','A.Guzman@Coopidrogas.Com.Co'),
    ('Denis Lorena Pulido Calderón','D.Pulido@Coopidrogas.Com.Co'),
    ('Néstor Torres','N.Torres@Coopidrogas.Com.Co'),
    ('Hugo Quito Figueredo','H.Quito@Coopidrogas.Com.Co'),
    ('Alba Patricia Carrillo Usaquén','A.Carrillo@Coopidrogas.Com.Co'),
    ('Faryd Castillo Santiago ','F.Castillo@Coopidrogas.Com.Co'),
    ('Mauricio  Quintero Guarin','M.Quintero@Coopidrogas.Com.Co'),
    ('Alberto Mora Roa','Almoro60@Hotmail.Com'),
    ('María Cecilia Pérez De Gutiérrez','Ceciliaperez@Une.Net.Co'),
    ('José Carmelo Rincón Vásquez','Jocariva@Hotmail.Com'),
    ('Luis Alberto Molina','Luismolina54@Yahoo.Es'),
    ('Stella Ordoñez De Silva','Stesysysyh@Hotmail.Com'),
    ('Luis Carlos Garzón','Suilcg2008@Hotmail.Com'),
    (NULL,'X'),
    ('Constanza Pieschacón Calis','C.Pieschacon@Coopidrogas.Com.Co'),
    ('Lida Lopez','Lidal@Coordinadora.Com /Coordinadora@Coordinadora.Com'),
    (NULL,'Direccion.Farmacenter@Copidrogas.Com.Co'),
    ('Carlos Bastos','Ceba82@Gmail.Com'),
    ('Duver Rivera','Duver.Rivera@Copservir.Co'),
    ('Idis Domínguez','Idispatricia19@Gmail.Com'),
    ('Abel Rocha ','Abel_Rocha@Copservir.Com'),
    ('Juan Carlos Bolivar ','Juanc_Bolivar@Copservir.Com'),
    ('Carlos Enrique Bastos ','Carlos_Bastos@Copservir.Com'),
    (NULL,'Diana.Trujillo@Corbeta.Com.Co'),
    (NULL,'Alejandravasquez@Corbeta.Com.Co ;   Alejandra.Vasquez@Alkosto.Com.Co'),
    (NULL,'Ana.Henao@Corbeta.Com.Co'),
    (NULL,'Norma.Lopez@Colcomercio.Com.Co'),
    ('Maria Cecilia Gonzalez','Mcgonzalez@Corona.Com.Co'),
    ('Maria Cecilia Gonzalez','Mariaceciliagonga@Gmail.Com'),
    ('Marta Marina Naira Reina ','Marta.Naira@Dinant.Com'),
    ('Michelle Gálvez ','Michelle.Galvez@Dinant.Com'),
    ('Carlos Ruiz','Carlos.Ruiz@Somoscmi.Com'),
    ('Jorge Enrique Trujillo Sánchez','Directorejecutivo@Puntoazul.Com.Co'),
    (NULL,'Gerencia@Cosmeticosmarliou.Com'),
    ('Carolina  Ramirez','C.Ramirez@Rodher.Com.Co'),
    ('Vanessa Tovar','Vanessa@Creaturaestudio.Com'),
    ('Juanita Guio / Luisa Hernández','Juanita.Guio@Credibanco.Com /  Luisa.Hernandez@Credibanco.Com'),
    ('Diana Carolina Lisker ','Diana.Lisker@Cruzverde.Com.Co'),
    ('Andres Ernesto Russi Bermudez','Andres.Russi@Cruzverde.Com.Co'),
    ('Katerine  Ochoa Ramirez','Katerine.Ochoa@Cruzverde.Com.Co'),
    ('Daniela  Cuadra Bouffanais','Daniela.Cuadra@Cruzverde.Com.Co'),
    ('Catalina Arroyave','Catalina.Arroyave@Cruzverde.Com.Co'),
    ('Giovanny  Petrel Rodriguez','Giovanny.Petrel@Cruzverde.Com.Co'),
    ('Mauricio  Guerra ','Mauricio.Guerra@Cruzverde.Com'),
    ('Yuri Caterine Riveros Sanabria','Yuricaterine1208@Cruzverde.Com.Co'),
    ('Jimmy Alexander Cubillos B','Jimmy.Cubillos@Cruzverde.Com.Co'),
    ('Bibiana  Cepeda Garcia','Bibiana.Cepeda@Cruzverde.Com.Co'),
    ('Diego Fernando Charry Marroquín','Diego.Charry@Cruzverde.Com.Co'),
    ('Nicolás  Navarro Salas','Nicolas.Navarro@Cruzverde.Com.Co'),
    ('Adriana  Ardila Peña','Adriana.Ardila@Cruzverde.Com.Co'),
    ('Johanna  Ricaurte ','Johanna.Ricaurte@Cruzverde.Com.Co'),
    ('Martha  Maya ','Martha.Maya@Cruzverde.Com.Co'),
    ('Angela  Aldana ','Angela.Aldana@Cruzverde.Com.Co'),
    ('Fernando  Ruiz Gomez','Fruizco@Hotmail.Com'),
    ('Juan Guillermo Bolivar','Jbolivar@Cuerosvelez.Com'),
    ('Monica Maria Gaviria','Monikagaviria@Gmail.Com'),
    ('Alfredo Murillo','Dauper.Colombia@Gmail.Com'),
    ('Alfredo Murillo','Alfredo.Murillo@Dauper.Com.Br'),
    (NULL,'Alvarogonzalez@Datosclaros.Com'),
    (NULL,'Cpalacios@Dersa.Com.Co '),
    (NULL,'Jrojas@Dersa.Com.Co'),
    (NULL,'Yriosb@Dersa.Com.Co'),
    (NULL,'Davella@Dersa.Com.Co'),
    (NULL,'Acardozo@Dersa.Com.Co'),
    (NULL,'Dbyfield@Dersa.Com.Co'),
    (NULL,'Mvasquez@Zonafrancabogota.Com'),
    (NULL,'Mcabrejo@Dersa.Com.Co');
INSERT INTO Base_Consolidada_Asistentes_Catman VALUES
    ('Denise Lãƒâ³Pez  ','Denise.Lopez@Diageo.Com'),
    (NULL,'Carolina.Silva@Diageo.Com'),
    ('Daniela Espinosa','Daniela.Espinosa@Diageo.Com'),
    (NULL,'Jose.Varsallona@Diageo.Com'),
    (NULL,'Ramiro.Villalobos@Diageo.Com'),
    (NULL,'Katherine.Schafer@Diageo.Com'),
    (NULL,'Paula.Larota@Diageo.Com'),
    (NULL,'Carolina.Gutierrez@Diageo.Com'),
    (NULL,'Jorge.Rubio@Diageo.Com'),
    (NULL,'Ramon.Garcia@Diageo.Com ; Ramon.Coronado@Diageo.Com'),
    ('Liliana Maria Dueñas Silva','Liliana.Duenas@Dianacorporacion.Com'),
    ('Jasseth Dãƒâ­Az','Jdiazh@Dichter-Neira.Com'),
    ('Martha Borda ','Marthabordag@Gmail.Com'),
    ('Juan Carlos Niño ','Jnino@Dichter-Neira.Com'),
    ('Martha Borda','Mborda@Dichter-Neira.Com'),
    (NULL,'Carolinafajardo@Dicorpsa.Com'),
    (NULL,'Francisco.Obando@Dicorpsa.Com'),
    (NULL,'Andreamonsalve@Dicorpsa.Com'),
    ('Johanna Ramos','Giovha52@Hotmail.Com'),
    ('Caren Bautista','Caren.Bautista@Grupodigitex.Com'),
    ('Maria Nemocon','Jefeecommerce@Monkeymarket.Com'),
    ('David Franco','David.Franco@Firmenich.Com'),
    ('Mauricio Olivia Brizio','Mauricio.Oliva@Dinant.Com'),
    ('Marcela Calero Ovalle','Marcela.Calero@Firmenich.Com'),
    ('Andrea Moreno','Andrea.Moreno@Firmenich.Com'),
    ('Luis Humberto Rivera Hernandez','Luis.Rivera@Dinant.Com'),
    ('Elliem Rico','Ellric@Directvla.Com.Co'),
    ('Marco Sãƒâ¡Nchez','Sanchez.Marco@Hotmail.Com'),
    ('Alejandra Muñoz ','Alejandra.Munoz@Dislicores.Com'),
    ('Johana Pulido','Jpulido@Cinecolor.Com'),
    ('Carlos Alejandro Velasquez Sanchez','Planeacion@Gaiacorp.Com.Co'),
    ('Jose Hugo Enciso Gaitan','Jhenciso@Gmail.Com'),
    ('Alexandra  Benavides ','Alexab@Axa.Com.Co'),
    ('Conf # 8 Ingrid Moreno','Imoreno@Axa.Com.Co'),
    ('Nelson  Molano ','Nelson@Axa.Com.Co'),
    ('Maria Camila Acuña ','Mcacuna@Gaiacorp.Com.Co'),
    ('Marcela Castro','Mercadeo@Axaconsumo.Com.Co'),
    ('Marcela Castro ','Laddymarce@Gmail.Com'),
    (NULL,'Gerencia@Makroaliados.Com'),
    (NULL,'Dislicores@Grupodistribucion.Com.Co'),
    (NULL,'Distrimars1949@Hotmail.Com'),
    ('Paola Gutierrez','Pgutierrez@Doingmkt.Com'),
    ('Shyamal  Kadukkatt ','Shyamkads@Gmail.Com'),
    ('Avinash  Mishra ','Avinashmishra@Drreddys.Com'),
    ('Luis  Delgadillo ','Luis.Delgadillo@Cruzverde.Com.Co'),
    ('Yener  Comas ','Karjim1@Hotmail.Com'),
    ('Magda Fernanda Torres Cruz','Magda.Torres@Cruzverde.Com.Co'),
    ('Andrea  Arrubla ','Andrea.Arrubla@Cruzverde.Com.Co'),
    ('Maria Alejandra Medina ','Maria.Medina@Dunnhumby.Com'),
    ('Bibiana Gomez ','Bibiana.Gomez@Dunnhumby.Com'),
    ('German Rivero ','German.Riberogarcia@Dunnhumby.Com'),
    ('Clara Botero','Clara.Botero@Dunnhumby.Com'),
    ('Juliana Muñoz','Juliana.Munoz@Dunnhumby.Com'),
    ('Paola Andrea Rubiano Carmona','Paola.Rubiano@Dunnhumvy.Com'),
    ('Diego Mateus ','Diego.Mateus@Dunnhumby.Com'),
    ('Juan Camilo Laverde ','Buzondelaverde@Gmail.Com'),
    (NULL,'Sebastian.Duque@Dunnhumby.Com'),
    ('Andres Ballen','Andres.Ballen@Dunnhumby.Com'),
    (NULL,'Daniel.Martelomunoz@Dunnhumby.Com '),
    (NULL,'Catalina.Zapata@Dyna01.Com'),
    (NULL,'German.Duran@Dyna06.Com'),
    (NULL,'Veronica.Urhan@Dyna09.Com'),
    (NULL,'Andres@Dynamo.Net'),
    ('Edwin Salazar','Edwinr.Salazar@Hotmail.Com'),
    ('Jose Bermudez','Jose.Bermudez@Edgewell.Com'),
    ('Luis Ruiz','Luisantonio.Ruiz@Edgewell.Com'),
    ('Camilo Arbelaez','Camilo.Arbelaez@Edgewell.Com'),
    (NULL,'Financiera.Colombia@Grupo-Sm.Com'),
    (NULL,'Editor@Revistaempresarial.Com'),
    ('Frann Palacio','Frann.Palacio@Exeltis.Com'),
    ('Frann Palacio Reyes','Frann_Palacio@Eficacia.Com.Co'),
    ('Jorge Andres Carvajal Carvajal','Carlo.Mario@Cplcolombia.Com'),
    (NULL,'Juan.Carvajal@Elrey.Com.Co'),
    (NULL,'Claudia.Paternina@Elrey.Com.Co'),
    ('Fredy Alexander Zárate Torres','Supervisor.Cadenas@Elrey.Com.Co'),
    ('Ciro Vargas','Ciro.Vargas@Elrey.Com.Co'),
    ('Nancy Sachica','Nancy.Sachica@Elrey.Com.Co'),
    (NULL,'Digitaljumper@Hotmail.Com'),
    (NULL,'Ibober@Eltiempo.Com'),
    (NULL,'Leopul@Eltiempo.Com'),
    (NULL,'Liljim@Eltiempo.Com'),
    (NULL,'Tatver@Eltiempo.Com'),
    ('Julián Mauricio Angel González','Jmosquera@Comercialnutresa.Com.Co'),
    ('Luis David Gómez Arias','Gomez_Luis_David@Lilly.Com'),
    ('Rafela Robalino','Rafaela.Robalino@Euromonitor.Com'),
    (NULL,'Presidencia@Easyfly.Com.Co'),
    (NULL,'Jhincapie@Aseocapital.Com.Co'),
    (NULL,'Claudia.Medina@Epm.Com.Co'),
    (NULL,'Juliana.Vallejo@Yr.Com'),
    (NULL,'Omar.Castillo@Yr.Com'),
    (NULL,'Alejandro.Beleno@Yr.Com'),
    ('Paola Monsivais','Paolam@Grobles.Mx'),
    (NULL,'Juanc.Correales@Energizer.Com'),
    ('Jorge Martin Leal Chappe','Jorge.Leal@Epidermique.Com'),
    ('Loni Anderson','Loniandersont@Gmail.Com'),
    (NULL,'Anacadavid@Esquema.Com'),
    (NULL,'Nubia.Bejarano@Essilor.Com.Co'),
    ('Karina  Fuenmayor ','Karina.Fuenmayor@Essity.Com'),
    ('Sandra Bustacara C','Sandra.Bustacara@Essity.Com'),
    ('Nicolas Penuela','Npenuela.Munoz@Gmail.Com'),
    ('Carolina Gómez','Cgomez@Estra.Com.Co'),
    (NULL,'Davidangulo@Spheramn.Com'),
    ('Fredy Alexander Garcia Ballen','Fredy.Garciab@Etb.Com.Co'),
    ('Nathaly Salazar','Nathaly.Salazar@Eterna.Com.Co'),
    ('Norma Constanza Puerto Gonzãƒâ¡Lez ','Norma.Puerto@Gmail.Com'),
    ('Nathali Salazar González','Nathali.Salazar@Eterna.Com.Co'),
    ('Norma Puerto','Norma.Puerto@Eterna.Com.Co'),
    ('Victor Manuel Castaño','Victor.Castano@Eterna.Com.Co'),
    ('Arlex Mejia Lopez','Ame@Galenicum.Com'),
    (NULL,'Evelyngestionhumana@Euroetika.Com'),
    ('Marco  Chaves ','Mchavess@Euroetika.Com'),
    ('Andrés  Orozco ','Acceso@Euroetika.Com'),
    ('Germán Enrique García Hoyos','Mercadeo@Euroetika.Com'),
    ('Luz Elena Amaya Plata','Gerenteventas@Euroetika.Com'),
    ('Edna Rocio Echeverría Ariza','Edna.Ariza@Eurofarmacolombia.Com.Co'),
    ('Alvaro  Del Castillo Rangel','Alvaro.Delcastillo@Eurofarmacolombia.Com.Co'),
    (NULL,'Jefe.Trade_Marketing@Evedisa.Com.Co'),
    (NULL,'Anyela.Torres.P@Hotmail.Com'),
    (NULL,'Carolina.Rodríguez@Evolutionplastic.Com'),
    ('Ana Cristina Ochoa','Anacristina.Ochoa@Exeltis.Com'),
    ('Sandra Eliana Suarez Lizarazo','Sandra.Suarez@Exeltis.Com'),
    ('Laura Igna Andrea Gonzalez','Laura.Igna.Gonzalez@Exeltis.Com'),
    ('Maria Alejandra Alonso','Alejandra.Alonso@Exeltis.Com'),
    (NULL,'Sandy.Calderon@Exeltis.Com'),
    ('Natalia Ojeda','Natalia.Ojeda@Faber-Castell.Com.Co'),
    (NULL,'Yolanda.Contreras@Elrey.Com.Co'),
    (NULL,'Linda.Montoya@Elrey.Com.Co'),
    ('Jorge Lisauskas','Jorge@Fb.Com'),
    ('Daniel Martelo ','Danmartelo@Falabella.Com.Co'),
    ('√Ångela  Escobar','Anglaes@Gmail.Com'),
    ('Wolfgang Henao Romero','Whenao@Fanalca.Com'),
    ('Monica Andrea Rodriguez Gomez','Monica.Rodriguez@Farmadecolombia.Com.Co'),
    ('Harold  Karam ','Harold.Karam@Farmadecolombia.Com.Co'),
    ('Botero  Camilo Andres','Camilo.Botero@Farmadecolombia.Com'),
    ('Carlos Martinez','Mercadeo@Grupojinca.Com'),
    ('Carlos Martínez','Carlos.Contreras@Fahorro-Ext.Com.Mx'),
    ('Patricia  Garcia ','Asohle@Chinoin.Com'),
    (NULL,'Fabian.Quilismal@Farmasanitas.Com'),
    (NULL,'Isabel.Quintero@Farmasanitas.Com'),
    (NULL,'Juan.Silva@Farmasanitas.Com'),
    (NULL,'German.Ramirez@Farmasanitas.Com'),
    (NULL,'Alexandra.Laverde@Farmasanitas.Com'),
    (NULL,'Clara.Tavera@Farmasanitas.Com'),
    (NULL,'Katherine.Ruiz@Farmasanitas.Com'),
    ('Claudia Caucali  ','Ccaucali05@Yahoo.Es'),
    (NULL,'Jrivera@Fedco.Com.Co'),
    (NULL,'Mvega@Fedco.Com.Co'),
    (NULL,'Mvega@Fedco.Com.Co ; Mmontanez@Fedco.Com.Co'),
    (NULL,'Fedco@Fedco.Com.Co'),
    (NULL,'Jessica.Ramos@Cafedecolombia.Com'),
    (NULL,'Luis.Londono@Cafedecolombia.Com '),
    (NULL,'Edgar.Hernandez@Cafedecolombia.Com'),
    (NULL,'Victor.Trujillo@Cafedecolombia.Com'),
    ('Rafael Antonio España ','Rafaelespana@Fenalco.Com.Co'),
    ('Fernando Rojas','Frojasramirez@Yahoo.Com'),
    ('David Sierra','David.Sierra@Ferrero.Com'),
    ('Daniel Cáceres','Daniel.Caceres@Ferrero.Com'),
    ('Juan Manuel Rodríguez Morales','Juan.Rodriguez@Ferrero.Com'),
    ('Laura Martínez','Laura.Martínez@Ferrero.Com'),
    ('Laura Martinez','Arual15_30@Hotmail.Com'),
    ('Laura Martinez Chavarro','Arual1630@Gmail.Com'),
    ('Karol Mantilla Atuesta','Coordinadormercadeo@Ferreterialdia.Com'),
    ('Bernardo Perez ','Bmperezh@Gmail.Com'),
    ('Jose Mauricio Espinel López','Jses@Ferring.Com'),
    ('Jose Mauricio Espinel López','Josemauricio.Espinel@Ferring.Com'),
    ('Daniela Cardenas Vasquez','Daniela.Cardenas@Firmenich.Com'),
    (NULL,'Carlos.Contreras@Firmenich.Com'),
    ('Carlos Del Valle','Carlos.Del_Valle@Outlook.Com'),
    ('Nathalie  Quintero ','Nathalie.Quintero@Fmc-Ag.Com'),
    (NULL,'Kabi.Col.Sac@Fresenius-Kabi.Com'),
    ('Olga Lucia Franco Cardenas','Olga.Franco@Fresenius-Kabi.Com.Co'),
    ('Paula  Gonzalez ','Paulaj.Gonzalez@Fmc-Ag.Com'),
    ('Carolina  Sanchez Rojas','Carolina.Sanchez@Fmc-Ag.Com'),
    ('Camila  Santos Mateus','Camila.Santos@Fmc-Ag.Com'),
    ('Laura J. Leal Castro','Laura.Leal@Freskaleche.Com.Co'),
    (NULL,'Comunicaciones@Frisby.Com.Co'),
    (NULL,'Amonroy@Frisby.Com.Co ; Nhuertas@Frisby.Com.Co'),
    (NULL,'Jbeltran@Frisby.Com.Co'),
    (NULL,'Laura.Medina@Pepsico.Com'),
    (NULL,'Servicioalciente@Fueradeserie.Com.Co'),
    ('Mariana  Viñas ','Mariana.Vinas@Galderma.Com'),
    ('Maria Camila Gonzalez A.','Mariacamila.Gonzalez@Galderma.Com'),
    ('Jean  Pierre Dulcey','Jeanpierre.Dulcey@Galderma.Com'),
    (NULL,'Lsepulvedar@Gascol.Com.Co'),
    (NULL,'Tu54Lux@Gaslux.Com.Co'),
    ('Misael  Perez ','Misael.Perez@Gedeonrichter.Eu'),
    ('Jorge Eliecer Cáceres Castellanos','Jorge.Caceres@Gedeonrichter.Eu'),
    (NULL,'Solo Reciben En Físico'),
    ('Albert Escalera Esteban','Alberto.Escalera@Genmills.Com'),
    ('Claudia Catalina Marin ','Catalina.Marin@Genmills.Som'),
    ('Paula Mayorga','Lina.Navas@Loreal.Com'),
    ('Fabián Sviercovich','Fabian.Sviercovich@Gm.Com'),
    (NULL,'Cfernandez@Genommalab.Com '),
    (NULL,'Cesar.Martinez@Gerfor.Com'),
    ('Juan Vargas','Juan.Vargas@Gfk.Com'),
    (NULL,'Liliana.Lopez@Bam.Com.Co'),
    ('Dionny  Montejo ','Dionny.A.Montejo@Gsk.Com'),
    ('Sergio Espinosa ','Sergio.A.Espinosa@Gsk.Com'),
    ('Nicolas Guzman ','Christian.N.Guzman@Gsk.Com '),
    ('Marcela Merizalde ','Adriana.M.Merizalde@Gsk.Com'),
    ('Andres Torres Valencia','Antova90@Hotmail.Com'),
    ('Claudia  Franco ','Claudia.L.Franco@Gsk.Com'),
    ('Elizabeth  Pinzon Devia','Elizabeth.Pinzon@Glenmarkpharma.Com'),
    ('Mauricio  Guerra Martinez','Mauricio.Guerra@Glenmarkpharma.Com'),
    ('Nelson Rodriguez ','Nrodriguezr@Gloria.Com.Co'),
    ('Paola Beltran ','Pandrea_7@Hotmail.Com'),
    ('Fabian Rodriguez','Frodriguezc@Gloria.Com.Co'),
    ('Leydi Arenas','L.Arenas@Gloria.Com.Co'),
    ('Angelica Monsalve','Amonsalve@Gloria.Com.Co'),
    ('Jennifer Beltran','Jbeltran@Gloria.Com.Co'),
    ('Nelson Rodriguez','Nrodriguez.R1510@Gmail.Com'),
    ('Paola Beltran','P.Beltran@Gloria.Com.Co'),
    (NULL,'Juridico@Biomax.Co'),
    ('Elena Yepes ','Elena.Yepes@Ddbcol.Com.Co'),
    ('Melissa Jaramillo ','Melissa.Jaramillo@Gotogether.Com.Co'),
    ('Melissa Jaramillo','Melissa.Jaramillo@Gotogether.Comn.Co'),
    ('Yohn Jarrinson Carrillo Palacios ','Yohn.Carrillo@Grandbay-Corp.Com'),
    ('Rocio Barona','Rbarona2015@Hotmail.Com'),
    (NULL,'Aluna@Grasco.Com'),
    (NULL,'Lgutierrez@Grasco.Com'),
    (NULL,'Adelgado@Grasco.Com'),
    ('Mariana Giraldo Castro','Magiraldo@Groupeseb.Com'),
    ('Juliana Santa María Saldarriaga','Jusantamaria@Groupeseb.Com'),
    ('Juliana Santa María Saldarriaga','Jusntamaria@Groupeseb.Com'),
    ('Alejandra Jaramillo Perez','Aljaramillo@Groupeseb.Com'),
    ('Ana Maria Castaño','Amcastano@Groupeseb.Com'),
    ('Natalia Rojas','Narojas@Groupeseb.Com'),
    ('Harold  Rodriguez Gonzales','Harold.Rodriguez@Grunenthal.Com'),
    (NULL,'Gonzalo.Monroy@Grupobimbo.Com'),
    ('Alexander Montoya','Alexander.Montoya@Grupobios.Co'),
    ('Diana Carolina Calderón ','Carolina.Calderon@Grupobiotoscana.Com'),
    ('Jonathan Battaglini','Battaglini.J@Grupo-Cala.Com'),
    ('Pablo Comparini ','Pablo.Comparini@Gmail.Com'),
    ('Daniel Francisco  Cabal Valdes ','Danielfrancisco.Cabal@Gmail.Com'),
    ('Martin Prera','Mprera@Distelsa.Com.Gt'),
    (NULL,'Camartinez@Grupo-Exito.Com'),
    ('Laura Leon','Lmleont@Grupo-Exito.Com'),
    ('Luz Velasquez','Lvelasquezg@Grupo-Exito.Com'),
    ('Jenny Orrego','Jorregoc@Grupo-Exito.Com'),
    ('John Fredy Gutiérrez','Fredy.Gutierrez@Exito.Com'),
    ('Julian Suárez Puerta','Jsuarezp@Grupo-Exito.Com'),
    (NULL,'Edisson.Diaz@Grupo-Exito.Com'),
    (NULL,'Erikabibiana.Torres@Grupo-Éxito.Com'),
    ('Marcela  Díaz ','Mdiaz@Grupo-Exito.Com'),
    (NULL,'Jose.Betancur@Grupo-Exito.Com'),
    ('Marco Aurelio Sanchez ','Marcose@Grupofamilia.Com'),
    ('Camila Holguin Pineda','Camilahop@Grupofamilia.Com'),
    ('Tatiana Zapata','Tatianazd@Familia.Com.Co'),
    ('Santiago Velasquez Munera','Santiagovm@Familia.Com.Co'),
    ('Angela Maria Escobar ','Angelaem@Familia.Com.Co');
INSERT INTO Base_Consolidada_Asistentes_Catman VALUES
    ('Diana Marcela Osorio ','Dianaom@Familia.Com.Co'),
    ('Maria Jimena Rengifo','Mrengifo@Gruposura.Com.Co'),
    ('Carolina Castaño Restrepo','Carolina.Castano@Gco.Com.Co'),
    ('Andres Felipe Solano Guarin','Andres@Grupodot.Com'),
    ('Juan Pablo Burgos ','Juan.P.Burgos@Gsk.Com'),
    (NULL,'Andrea.L.Garcia@Gsk.Com'),
    ('Andrea  Rodas Puerto','Andrea.A.Rodas@Gsk.Com'),
    ('Javier  Vaca ','Javier.D.Vaca@Gsk.Com'),
    ('Brian  Castro ','Brian.8.Castro@Gsk.Com'),
    ('Angie  Sánchez Victoria','Angie.J.Sanchez@Gsk.Com'),
    (NULL,'Melissa.X.Villegas@Gsk.Com ---- Pablo.X.Trujillo@Gsk.Com'),
    ('Wilson Gerardo Ulloa Gomez','Wilson.G.Ulloa@Gsk.Com'),
    (NULL,'Lindaortiz@Gspcorp.Com'),
    ('Valentina  Osorio',' Valentina.Osorio@Gwspirits.Com'),
    ('Claudia Penagos','Claudia.Penagos@Haceb.Com'),
    ('Santiago Alvarez','Santiago.Alvarez@Haceb.Com'),
    ('Diego Fernando Arana Moreno','Diego.Arana@Haceb.Com'),
    ('Camilo Sanchez','Camilo.Sanchez@Haceb.Com'),
    ('Consuelo Carrascal','C.Carrascal@Hv.Com.Co'),
    ('Andrea Galindo ','A.Galindo1@Hv.Com.Co'),
    ('Marcela Acosta ','M.Acosta@Hv.Com.Co'),
    ('Sergio David Martinez Sarmiento ','Sd.Martinez@Hv.Com.Co'),
    ('Daniela Arce Ramos ','D.Arce@Hv.Com.Co'),
    ('Dany Malagon','Dj.Malagon@Hv.Com.Co'),
    ('Beatriz Blum','Be.Blum@Hv.Com.Co'),
    ('Luz Helena Vargas','Lh.Vargas@Hv.Com.Co'),
    ('Carolina Vidal ','C.Vidal@Hv.Com.Co'),
    ('Daniela Cardenas Isaza ','D.Cardenas@Hv.Com.Co'),
    ('Jaime Valencia ','Ja.Valencia@Hv.Com.Co'),
    ('Dina Muñoz ','Dm.Munoz@Hv.Com.Co'),
    ('Juan Camilo Carmen Velasquez','Jc.Carmen@Hv.Com.Co'),
    ('Adalgiza Valdes','A.Valdes@Hv.Com.Co'),
    (NULL,'P.Zorrilla@Harineradelvalle.Com'),
    (NULL,'Jc.Henao@Harineradelvalle.Com ; Comunicaciones@Harineradelvalle.Com'),
    (NULL,'Mferrero@Harineradelvalle.Com'),
    ('Jackson Rodriguez Sanchez','J.Rodriguez@Hv.Com.Co'),
    ('Juan Bello','Juan.Bello@Hasbro.Com'),
    ('Santiago Salazar','Santiago.Salazar@Hasbro.Com'),
    ('Jose Luis Gutiérrez ','Jose.Gutierrez@Hasbro.Com'),
    ('Wilson  Gonzalez ','Healthdermasas@Gmail.Com'),
    ('Esteban David Orjuela Murillo','Esteban.Orjuela@Heel.Com.Co'),
    ('Adriana  Herrera ','Adriana.Herrera@Heel.Com.Co'),
    (NULL,'Andrea.Freitas@Heineken.Com.Br'),
    (NULL,'Chiara.Martini@Heineken.Com.Br'),
    ('Paola Marquez','Paola.Marquez@Heladospopsy.Com'),
    ('Juliana Nieto ','Juliana.Nieto@Henkel.Com'),
    ('Karina Gomez ','Karinagomezm@Hotmail.Com'),
    ('Marãƒâ­A Camila Guerrero Torres ','Mcamila_Torres@Outlook.Com'),
    ('Camila Pena','Camila.Penasilva@Henkel.Com'),
    ('Liliana Murcia','Liliana.Murcia@Henkel.Com'),
    ('Diana Tasama','Diana.Tasama@Henkel.Com'),
    ('Andres Perilla','Andres.Perilla@Henkel.Com'),
    ('Andres Londoño','Andreslg3089@Gmail.Com'),
    ('Catalina Cifuentes','Catalina.Cifuentes@Henkel.Com'),
    ('Juanita Ospina','Juanita.Ospina@Henkel.Com'),
    ('Rafael Orellana Y.','Rafael.Orellana@Henkel.Com'),
    ('Alejandro Gutierrez','Alejandro.Gutierrez-Naranjo@Henkel.Com'),
    ('Lorena Romero','Lorena.Romero@Henkel.Com'),
    ('Yareniz Calderon','Yaredcm@Gmail.Com'),
    (NULL,'Fredy.Moreno@Henkel.Com'),
    (NULL,'Eliana.Rodriguez@Henkel.Com ; Katherin.Ruiz@Henkel.Com'),
    (NULL,'Ernesto.Sierra@Henkel.Com'),
    ('Nicolas Moreno','Nicolas.Moreno@Henkel.Com'),
    ('Camilo Otoya','Camilo.Otoya@Henkel.Com'),
    ('Enrique Madronero','Emadronero@Yahoo.Com'),
    ('Haydee Hernãƒâ¡Ndez  ','Hhernandezo@Herdez.Com'),
    ('Andrés Rodriguez','Andresr45@Hotmail.Com'),
    ('Bernardo Garcia Gomez','Bgarciag@Homecenter.Co'),
    (NULL,'Pbernal@Homesentry.Net'),
    (NULL,'Larmenta@Homecenter.Co'),
    (NULL,'Vmolina@Homecenter.Co'),
    (NULL,'Lcetina@Homecenter.Co'),
    ('Jaime Arenas','Jaime.Arenas80@Gmail.Com'),
    ('Felipe Valencia','Felipe.Valencia.Delgado@Hp.Com'),
    ('Pablo Murillo','Pablo.Murillo1@Hp.Com'),
    ('Cecilia Castillo','Cmcastillogil@Gmail.Com'),
    (NULL,'Marketco@Co.Ibm.Com'),
    ('Francisco Alvarez','Franciscoalvarez2390@Gmail.Com'),
    ('Francisco Alvarez Jaimes ','Franciscoalvarez2380@Gmail.Com'),
    (NULL,'Hsalazar@Incauca.Com'),
    ('Victoria Coll','Victoriacollg@Gmail.Com'),
    (NULL,'Julio.Gomes@Incontext.Consulting'),
    (NULL,'Majogogue92@Hotmail.Com'),
    ('Julian Hernandez','Jdbaez14@Gmail.Com'),
    ('Edgar Villalba','Edgarenriquevillalba@Hotmail.Com'),
    ('Lina Jaramillo','Lina.Jaramillo1@Gmail.Com'),
    ('Paola Ramãƒâ­Rez ','Paolaaramirezq@Hotmail.Com'),
    ('Santiago Martinez ','Smartinez@Indices.Com.Co'),
    ('Paula Andrea Ramirez','Jefeproducto@Indulatex.Com.Co'),
    (NULL,'Gmvelasquez@Serviciosnutresa.Com'),
    (NULL,'Bmolina@Alimentoscarnicos.Com.Co'),
    (NULL,'Lherrerau@Zenu.Com.Co'),
    ('Hassel  Diaz','Hassel.Diaz@Haceb.Com'),
    ('Marcela Cruz Amaya','Marcela.Cruz@Haceb.Com'),
    ('Angela Ossa','Angela.Ossa@Haceb.Com'),
    ('Viviana Soto','Viviana.Soto@Haceb.Com'),
    ('Julian Herrera Henao','Julian.Herrera@Haceb.Com'),
    ('Christian Chavez Barquero','Christian.Chavezbarquero1@Gmail.Com'),
    ('Mauela Caballero Manuela Caballero','Manuela.Caballero@Infiniamobile.Com'),
    (NULL,'Comercial@Ingeniocarmelita.Com'),
    (NULL,'Ghumana@Ingeniocarmelita.Com '),
    (NULL,'Logistica@Ingeniocarmelita.Com'),
    ('Carlos Alejandro Espejo','Laura.Caballero@La.Spectrumbrands.Com'),
    (NULL,'Colombia@Gruporoble.Com'),
    (NULL,'Contabilidad@Bu.Com.Co'),
    ('Dario Herrera','Dario.Herrera@Hotmail.Com'),
    ('Maria Raquel Gomez','Mraquelgomezl@Gmail.Com'),
    ('Alison Pineda','Alison.Pineda@Irixapp.Com'),
    (NULL,'Daniel.Vasquez@Irixapp.Com'),
    ('Victoria Vargas García','Victoria.Vargasgarcia@Hotmail.Com'),
    ('Alejandro Sarzosa','Alejsandrosarzosa@Avicolasantarita.Com'),
    ('Mauricio Del Gaudio','Mauricio.Delgaudio@Gmail.Com'),
    ('Lina Maria Ruiz Macchi ','Macchi2@Hotmail.Com'),
    (NULL,'Mercadeomedellin@Jaibel.Com'),
    ('Juan Felipe Otálora Vega','Jotalora@Its.Jnj.Com'),
    ('Benedicte  Agnano ','Bagnano@Its.Jnj.Com'),
    ('Diego Chavarro','Diego.Chavarro@Jeronimo-Martins.Com'),
    ('Mario Payan','Mario.Payan@Jeronimo-Martins.Com'),
    ('Manuela Fernández','Manuela.Fernandez@Jeronimo-Martins.Com'),
    ('Cristian Velandia','Cvelandia@Jgb.Com.Co'),
    ('Carolina Vivas','Cvivas@Jgb.Com.Co'),
    ('Laura Muñoz Prado','Lamunoz@Jgb.Com.Co'),
    ('Laura Martinez Padilla ','Lmartinez@Jgb.Com.Co'),
    (NULL,'Angelica.Escobar@Jgb.Com.Co'),
    (NULL,'Diego.Arroyave@Jgb.Com.Co'),
    (NULL,'L.Ivanes@Jgb.Com.Co'),
    ('Lucía Fonseca','Krysia.Bonilla@Kcc.Com'),
    ('Felipe Salazar Urrea','Fsalaza1@Its.Jnj.Com'),
    ('Jorge Luis Vãƒâ©Lez Mayor ','Jvelez12@Its.Jnj.Com'),
    ('Oscar Eduardo Duque Vanegas ','Oduqueva@Its.Jnj.Com'),
    (NULL,'Mruiz@Its.Jnj.Com'),
    (NULL,'Mvelas11@Its.Jnj.Com ; Moninvel@Hotmail.Com'),
    ('Valentina Morales','Vmoral11@Its.Jnj.Com'),
    ('Lina Maria Ruiz  ','Lruiz1@Its.Jnj.Com'),
    ('Mariana Ocampo  ','Mocampoo@Its.Jnj.Com'),
    (NULL,'Jpereyr2@Its.Jnj.Com'),
    (NULL,'Mherre33@Its.Jnj.Com'),
    (NULL,'Pvalderr@Its.Jnj.Com'),
    (NULL,'Ahenao@Its.Jnj.Com'),
    (NULL,'Vrestrep@Its.Jnj.Com'),
    (NULL,'Pzamoran@Its.Jnj.Com'),
    (NULL,'Mtorelli@Its.Jnj.Com'),
    (NULL,'Ksilva8@Its.Jnj.Com'),
    ('Laura Isabel Lãƒâ³Pez ','Llopezab@Its.Jnj.Com'),
    ('Juan  Plat√≠N','Juancplatin@Qgmail.Com'),
    ('Juan Camilo Platín Cano','Juancplatin@Gmail.Com'),
    (NULL,'Maria.Jose.Gnecco@Jpmorgan.Com'),
    ('Jaime García','Jaime.Garcia@Kantar.Com'),
    ('Marcela Jiménez','Gerencia.General@Elarrozal.Co'),
    ('Lourdes Bran','Lourdes.Bran@Kantar.Com'),
    ('Carolina Andrade','Carolina.Deandrade@Kantar.Com'),
    ('Alfredo Mesa','Alfredo.Mesa@Kantar.Com'),
    ('Stefano Sesana','Stefano.Sesana@Kantar.Com'),
    ('Cecilia Ballarin','Cecilia.Ballarin@Kantar.Con'),
    ('Aura Boada ','Aura.Boada@Kantar.Com'),
    ('Edwin Alberto Tachack Fajardo','Edwin.Tachack@Gmail.Com'),
    ('Yara Patricia Hurtado Sanchez','Yara.Hurtado18@Gmail.Com'),
    ('Carolina Luzia De Andrade ','Carolina.Deandrade@Kantarworldpanel.Com'),
    (NULL,'Juan.Caro@Kantarworldpanel.Com'),
    (NULL,'Karen.Mendoza@Kantarworldpanel.Com'),
    ('Marcela Brenes','Marcela.Brenes@Kcc.Com'),
    (NULL,'Eliana.Ulloa@Kellog.Com'),
    ('Patricia Jimãƒâ©Nez ','Patricia.Jimenez@Hotmail.Com'),
    ('Mercedes Zarich Juaristi ','Mercedes.Zarich@Kellogg.Com'),
    ('Camila Sandoval Rosero','Camila.Sandoval@Kellogg.Com'),
    (NULL,'Alejandro.Jaramillo@Kellog.Com'),
    ('Nancy Rocio Huertas Vega','Nrhuertas@Keralty.Com'),
    ('Jhonny Alfonso Hoyos López','Jhoyos@Keralty.Com'),
    ('Camila Emilia Herrera','Cherrera@Khiron.Ca'),
    ('Maria Alessandra De Leon Fadul','Mdeleon@Khiron.Ca'),
    ('Catalina Peña Pineda','Cpena@Khiron.Ca'),
    ('Ingrid Alzate','Jalzate@Khiron.Ca'),
    ('Felipe Rengifo','Rengifof03@Gmail.Com'),
    ('Ma Camila Velasquez ','Maria.Velasquez@Kcc.Com'),
    ('Krysia Bonilla','Julián.Angel@Elarrozal.Co'),
    ('Gerardo Escolan','Gerardo.A.Escolan@Kcc.Com'),
    ('Claudia Torres','Claudia.Torres@Kcc.Com'),
    ('Carolina Torres','Carolina.Torres.H@Kcc.Com'),
    ('Mariela Herrera','Mercadeo@Sccala.Com'),
    ('Paulo Perdomo','Pauloandres.Perdomo@Kcc.Com'),
    (NULL,'Atencionalconsumidor@Kcc.Com'),
    ('Carolina Gomez','Carol.Nose@Nose.Com'),
    ('Tatiana Cardenas','Taty.Nose@Nose.Com'),
    ('Viviana Bajaire ','Viviana.Bajaire@Gmail.Com'),
    ('Carolina  Sarria Romero','Csarria@Polanova.Com'),
    ('Lina Maria Buitrago','Linabuitrago80@Hotmail.Com'),
    ('Neyla Tatiana Marín Rodriguez ','Neylat.Marinr@Konradlorenz.Edu.Co '),
    ('John Jairo Pulgarin Manzano','Kostazul@Kostazul.Com'),
    ('Cristian David','David.Vasquez@Loreal.Com'),
    ('Adriana Tovar','Adriana.Tovar@Camporeal.Co'),
    (NULL,'Paula.Cardona@La14.Com'),
    (NULL,'Manuel.Castrillon@La14.Com'),
    ('Jorge San Martin','Sanmartin.Jorge87@Gmail.Com'),
    ('Douglas Espinoza Vãƒâ¡Squez ','Djespino56@Gmail.Com'),
    ('Andrea Medina Forero','Andrea_Apmf@Hotmail.Com'),
    (NULL,'Ana.Ortega@Aliar.Com.Co'),
    (NULL,'Tatiana.Robles@Lariviera.Com.Co'),
    ('Angela Sanchez Luz Alba Henao','Luz.Nose@Nose.Com'),
    ('Jaime Fernando Duran ','Jaime.Duran@Pharmetiquelabs.Com'),
    ('Yohana  Rubio ','Joanna.Rubio@Pharmetiquelabs.Com'),
    ('Luz Miryam Guarin ','Luz-Miryam.Guarin@Servier.Com'),
    ('Viviana Montoya Cataño','Mercadeo@Mariasalome.Com'),
    ('Lina Maria Castillo ','Lina.Castillo@Bussie.Com.Co'),
    ('Deisy Milena Abril ','Deisy.Abril@Bussie.Com.Co'),
    (NULL,'Gilma.Ruiz@Chalver.Com.Co'),
    (NULL,'Luisa.Restrepo@Chalver.Com.Co'),
    (NULL,'Luzmery.Angarita@Chalver.Com.Co'),
    (NULL,'Olga.Palacios@Chalver.Com.Co'),
    (NULL,'Sandra.Serrano@Chalver.Com.Co'),
    ('Keila Rodriguez Solano ','Krodriguez@Cofarma.Com'),
    (NULL,'Compras@Cofarma.Com'),
    (NULL,'Impuestos@Joliedevogue.Com'),
    ('Alejandra  Montoya','Alejandra.Montoya@Higietex.Com.Co'),
    ('Emelit Patricia Roca Sanjuan','Inteligenciamercados@Incobra.Com'),
    ('Andrés  Castro Robayo','Analista.Intmercados@Incobra.Com'),
    (NULL,'Cesar.Bravo@Lasante.Com.Co'),
    (NULL,'Ricardo.Usaquen@Lasante.Com.Co'),
    ('Nancy  De La Torre ','Ndelatorre@Laboratorioslegrand.Com'),
    ('Diego  Gallo ','Dgallo@Laboratorioslegrand.Com'),
    (NULL,'Lpbonilla@Recamier.Com'),
    (NULL,'Agonzalez@Recamier.Com'),
    (NULL,'Jcifuentes@Recamier.Com'),
    ('Ingrid  Vivienda Jaimes','Ingrid.Pimienta@Servier.Com'),
    ('María José Fernández ','Maria-Jose.Fernandez@Servier.Com'),
    ('Diana Carolina Bolívar Cuadrado','Diana.Bolivar@Servier.Com'),
    ('Armando  Valera Galeano','Avalera10@Hotmail.Com'),
    ('Javier Fernando Bermudez Barragan','Javier.Bermudez@Laboratoriossudamericanos.Com'),
    ('Javier Fernando Bermudez Barragan ','Javier.Bermudez@Irex.Com.Co'),
    (NULL,'Jvelez@Rysglobales.Com.Co'),
    ('Beatriz  Cabrera Franco','Bcabrera@Laboratorioslegrand.Com'),
    (NULL,'Planeacion@Lehit.Com.Co ; Servicioalcliente@Lehit.Com.Co'),
    ('Blanca Muños','Blanca.Munoz@Levapan.Com'),
    (NULL,'Oscar.Cortes@Levapan.Com'),
    (NULL,'Carolina.Gaviria@Levapan.Com'),
    ('Juan Carlos Jiménez Ordoñez','Juan.Jimenez@Levapan.Com'),
    ('Andres Daza','Andres.Daza@Levapan.Com'),
    ('Daniel  Botero ','Danbotero@Gmail.Com'),
    ('Francisco Mejia','Fmejia28@Hotmail.Com'),
    (NULL,'Jgrimaldo@Licenciasonline.Com'),
    ('Catalina Rodríguez Mejía','Catalina_Rodriguez@Liderpop.Com'),
    ('Elizabeth Sanchez ','Esanchez@Lindt.Com'),
    ('Mariana Taborda','Marianatabordaruiz@Gmail.Com'),
    ('Sergio Tarazona ','Tarazonaovalle@Gmail.Com'),
    ('Lisselote Marlene Ortiz Paulino','Lisseortiz@Hotmail.Com'),
    ('Jose Manuel Reinoso ','Jreinoso1519@Gmail.Com'),
    ('Edison Alejandro Palacios ','Palacios.Edison@Locatelcolombia.Com'),
    ('Scarlet  Navarro ','Navarro.Scarlet@Locatelcolombia.Com'),
    ('Diana Marcela Díaz','Diaz.Marcela@Locatelcolombia.Com'),
    ('Diana Maritza García','Garcia.Diana@Locatelcolombia.Com'),
    ('Jeanette García','Garcia.Jeanette@Locatelcolombia.Com');
INSERT INTO Base_Consolidada_Asistentes_Catman VALUES
    ('Nelson Palacio','Npalacio@Logicem.Co'),
    ('Andrea Chacon ','Achacon@Logyca.Com'),
    ('Juan Felipe Gomez Alvarado','Jgomez@Logyca.Com'),
    ('Marta  Guacaneme','Martha.Guacaneme@Loreal.Com'),
    ('Lina Maria Navas Rodriguez','Paula.Mayorgavergano@Gm.Com'),
    ('Andrés Yepes','Adriana.Martinez@Loreal.Com'),
    ('Andrea Beleno','Andreabelenoh@Gmail.Com'),
    ('Andrea Beleno','Andrea.Beleno@Loreal.Com'),
    ('Erika Martínez Sarmiento','Erika.Martinez@Loreal.Com'),
    ('Derly Rojas','Gerencia@Benditoarroz.Com'),
    ('Omar Bello','Jdorado@Alqueria.Com'),
    (NULL,'Cmora@Co.Loreal.Com'),
    ('Derly Fabiola Rojas Hernandez','Derly.Rojas@Loreal.Com'),
    ('Adriana Martinez','Mariela.Herrera.Hernandez@Gmail.Com'),
    (NULL,'Secrecompras@Lostreselefantes.Com'),
    (NULL,'Gerencia@Lostreselefantes.Com.Co'),
    (NULL,'Jairo@Lphant.Co'),
    (NULL,'Asistente@Gaseosasflorencianas.Com'),
    ('Henry  Puerto Peña','Hppe@Lundbeck.Com'),
    ('Jorge Benavides Muñoz','Laura.Gonzalez@Nielsen.Com'),
    ('Javier Ubaque Gutiãƒâ©Rrez  ','Javier.Ubaque@Makro.Com.Co'),
    ('Juan Yepes ','Juan.Yepes@Makro.Com.Co'),
    ('Laura Ramirez','Laura.Ramirez@Makro.Com.Co'),
    (NULL,'Jaddy.Gonzalez@Makro.Com.Co'),
    (NULL,'John.Londono@Makro.Com.Co'),
    (NULL,'Andres.Mejia@Makro.Com.Co'),
    (NULL,'Cesar.Abondano@Makro.Com.Co'),
    (NULL,'Carlos.Torres@Makro.Com.Co'),
    (NULL,'Carolina.Diaz@Makro.Com.Co'),
    (NULL,'Cristhian.Argaez@Makro.Com.Co'),
    (NULL,'Libardo.Ramirez@Makro.Com.Co'),
    (NULL,'Zuly.Garzon@Makro.Com.Co'),
    ('Genesis Morales','Genesis.Morales.G@Gmail.Com'),
    (NULL,'Ventas.Bogota@Manitoba.Com.Co'),
    (NULL,'Aseg.Calidad@Manitoba.Com.Co '),
    ('José Andres Chaves Somoza','Anchasom@Gmail.Com'),
    ('Cristian Leon','Cleon@Marcimex.Com.Ec'),
    ('Conf # 4 Enrique Casas','Ecasas19@Gmail.Com'),
    ('Juan Caviedes','Fcaviedes_30@Hotmail.Com'),
    ('Paola Rodriguez','Paola.Rodriguez@Effem.Com'),
    ('Sandra Torres Lara','Sandra.Torres1@Effem.Com'),
    ('Laura Echavarria','Laura.Echavarria@Effem.Com'),
    ('Paola Rodríguez','Paola.Rodriguezsan@Gmail.Com'),
    ('Nathalia Marulanda','Nathalia.Marulanda@Effem.Com'),
    ('Natalia Santa','Natalia.Santa@Effem.Com'),
    ('Daniela Gallego','Daniela.Gallego@Effem.Com'),
    ('Diego Alejandro Sanchez Manrique','Diego.Sanchez@Effem.Com'),
    ('Andrea Rodríguez ','Andrea.Rodriguez@Effem.Com'),
    ('Roxana Oliva B.','Roxana.Oliva@Effem.Com'),
    ('Paulina Vega ','Paulina.Vega@Effem.Com'),
    ('Maria Giraldo','Maria.Giraldo1@Effem.Com'),
    ('Mariana Mendez','Mariana.Mendez2@Effem.Com'),
    ('Diana Moreno','Diana.Moreno@Effem.Com'),
    ('Johana Colorado Valencia','Johana.Colorado@Effem.Com'),
    ('Paola Benavides','Paola.Benavides@Effem.Com'),
    ('Macarena Seminario','Macarena.Seminario@Effem.Com'),
    (NULL,'Nathalia.Reyes@Effem.Com'),
    ('Camila Jim√©Nez ','Camilajb@Gmail.Com'),
    (NULL,'Servicio.Clientes@Mattel.Com'),
    (NULL,'Gerencia@Gairacafe.Co'),
    ('Maria Alejandra Estrada','Maria.Estrada@Mccain.Com.Co'),
    (NULL,'Alejandra.Gomez@Co.Mcd.Com'),
    ('Lina Millan','Lina.Millan@Mccain.Com.Co'),
    ('Paula Garcia','Paula.Garcia@Mccain.Com.Co'),
    (NULL,'Yorlady.Santamaria@Rb.Com'),
    ('Catalina Olarte','Catalina.Larte@Mjn.Com'),
    ('Fabiana Aristizabal','Fabiana.Aristizabal@Rb.Com'),
    ('Julian Hernandez','Jdhernandez@Cremhelado.Com.Co'),
    (NULL,'Contacto@Meals.Com.Co'),
    ('Juan Guillermo Franco Gutierrez','Jgfranco@Cremhelado.Com.Com'),
    ('Verónica Arteaga','Varteaga@Cremhelado.Com.Co'),
    (NULL,'Abotero@Cremhelado.Com.Co'),
    (NULL,'Cespinosa@Cremhelado.Com.Co'),
    ('Bibiana  Sanchez Cardozo','Sanchezcardozobibiana@Gmail.Com'),
    ('Monica  Bustos ','Director.Mercadeo@Memphis.Com.Co'),
    ('Alvaro  Mayans ','Gerenciacomercial@Memphis.Com.Co'),
    ('Sandra Abadia','Sabadia@Mercadeoefectivo.Com'),
    (NULL,'Catalina.Botero@Rapp.Com.Co'),
    ('Carmen Martínez Giraldo','Carmen.Martinez@Mercadopago.Com.Co'),
    ('Zoleida  Hurtado ','Zoleida.C.Hurtado@Merckgroup.Com'),
    ('Federico  Ramirez ','Federico.Ramirez@Merckgroup.Com'),
    ('David  Montalvo ','David.Montalvo@Merckgroup.Com'),
    ('Andrés  Monroy ','Andres.Monroy@Merckgroup.Com'),
    ('Juan Cruz Alvarez Garcia','Juan-Cruz.Alvarez-Garcia@Merckgroup.Com'),
    ('Vicky  Vueltas Melo','Vicky.Vueltas@Merckgroup.Com'),
    ('Daniella Puerto','Daniella.Puerto.Navia@Merck.Com'),
    ('Juan David Pesca Macias','Juan.Pesca@Merckgroup.Com'),
    ('Luz  Gordillo ','Luz.Gordillo@Merckgroup.Com'),
    (NULL,'Mnarvaez@Microsoft.Com'),
    ('Juan Carlos Cuadros','Juancuadros@Mindbrand.Co'),
    (NULL,'Nicole.Munoz@Momentumww.Com'),
    ('Jorge Rosales','Jorge.Rosales2@Mdlz.Com'),
    (NULL,'Guillermo.Alfaro@Mdlz.Com'),
    ('Yoratzih Gaester','Noguey01@Hotmail.Com'),
    ('Andres Maldonado','A.Maldonado@Morenos.Com.Co '),
    ('Roberto Aranda','Analistacomercial@Morenos.Com.Co'),
    ('Julie Viviana Sanchez Nieto','Julie.Sanchez@Telefonica.Com'),
    ('Juan Ricardo Pãƒâ©Rez','Juan.Perez@Co.Nestle.Com'),
    ('Adriana Soto Barbosa ','Adriana.Soto@Co.Nestle.Com'),
    ('Ana Maria Duarte ','Ana.Duarte@Co.Nestle.Com'),
    ('Maria Hernandez','Maria.Hernandez@Co.Nestle.Com'),
    ('Vanessa Victoria H','Vannev.03@Gmail.Com'),
    ('Camila Gallo','Camila.Gallo@Co.Nestle.Com'),
    ('Camila Gallo','Camigallo1@Hotmail.Com'),
    ('Fabian Patiãƒâ±O','Fabian.Patino@Co.Nestle.Com'),
    ('Ana Maria Uribe Restrepo ','Ana.Uribe@Co.Nestle.Com'),
    ('Pia Illidge','Pia.Illidge@Co.Nestle.Com'),
    ('Galo Leroux','Galo_Ler21@Hotmail.Com'),
    ('Julian Angarita Valcarcel ','Julian.Angarita@Co.Nestle.Com'),
    ('Camilo Jimenez','Camilo.Jimenez@Co.Nestle.Com'),
    ('Claudia Mejia ','Claudia.Mejia@Co.Nestle.Com'),
    (NULL,'Virginia.Forero@Co.Nestle.Com'),
    (NULL,'Ricardo.Piedrahita@Co.Nestle.Com'),
    (NULL,'Servicio.Consumidor@Co.Nestle.Com'),
    (NULL,'Jose.Silva@Co.Nestle.Com'),
    (NULL,'Maria.Leyva@Co.Nestle.Com'),
    (NULL,'Mercadeo@Nicolukas.Com'),
    (NULL,'Ramses.Landaverde@Nielsen.Com - Ramses.Laverde@Nielsen.Com'),
    ('Camilo Sanchez','Camilo.Sanchez@Nielsen.Com'),
    ('Tonino  Ambrosio ','Tambrosio@Novamed.Com.Co'),
    ('Gloria Yulieth Osorio Rojas','Gosorio@Vnovamed.Com.Co'),
    ('Pedro  Gonzalez ','Pgonzalez@Novamed.Com.Co'),
    ('Luis Henry Feo Rincon','Hfeo@Novamed.Com.Co'),
    ('Luis Felipe Castillo Neira','Felipe.Castillo_Neira@Sandoz.Com'),
    ('Julián Giraldo','Jgiraldo@Novaventa.Com'),
    ('Estephania Giraldo Quintero','Egiraldo@Novaventa.Com'),
    ('Juan Carlos Perez Monsalve','Jcperez@Novaventa.Com'),
    ('Monica Zapata Castillo','Mzapata@Novaventa.Com'),
    (NULL,'Dmrivera@Novaventa.Com'),
    ('Julian Uribe Velasquez','Juribe@Novaventa.Com'),
    ('David Ramirez Robledo ','Dramirez@Novaventa.Com'),
    ('Maria Astrid Echavarria Franco ','Maechavarria@Novaventa.Com'),
    ('Tatiana Henao','Dhenaobe@Novaventa.Com'),
    ('Juan Camilo Zuluaga R.','Jczuluagar@Novaventa.Com'),
    ('Lina Julieth Alzate Bello','Lnjb@Novonordisk.Com'),
    ('Juan C Arias ','Jcnv@Novnonordisk.Com'),
    ('Diego Fernando Buriticá ','Dfbl@Novonordisk.Com'),
    ('Sebastian  Carrillo Pacheco','Cpsb@Novonordisk.Com'),
    ('Luz Aleyda Hernandez Vargas','Luzaleyda.Hernandez@Hotmail.Com'),
    ('Mauricio Jaschkowitz','Mauricio@Nutritionsol.Com'),
    ('Daniela Ruiz','Druizv@Comercialnutresa.Com.Co'),
    ('Janneth Castillo','Janneth.Castillo.Silva@Gmail.Com'),
    ('Felipe Aguilar Ochoa','Paxcautoservicios@Comercialnutresa.Com.Co'),
    ('Ivan Herrera ','Gerencia@Kionutri.Com'),
    (NULL,'404Tuckermark@Gmail.Com'),
    (NULL,'J.Gutierrez@Oberthur.Com'),
    ('Marco Antonio Peres','Infoobservatics@Uexternado.Edu.Co'),
    ('Álvaro Bohorquez','Alvaro.Bohorquez@Ofertia.Com.Co'),
    ('Daniel Zapata ','Daniel.Zapata@Offcorss.Com'),
    ('Stephany Caro','Scaro@Olimpica.Com.Co'),
    ('Pedro Garcia','Pedroluisgarciavallejo@Gmail.Com'),
    ('Aurelio De Castro ','Audecas@Hotmail.Com'),
    (NULL,'Ktorrenegra@Olimpica.Com.Co'),
    ('Pedro Garcia','Pgarcia02@Olimica.Com.Co'),
    ('Enrique Cabrera ','Enrique@Omnicommercelatam.Com'),
    ('Angãƒâ©Lica Aristizãƒâ¡Bal Rivas ','Mercadeo@Oncerazones.Com'),
    ('Edgar Sandoval A','Gerencia@Openmind.Com.Co'),
    ('Juan Rebolledo','Juan.Rebolledo@Optionsa.Com'),
    ('Juan Bernate','Juan.Bernate@Oracle.Com'),
    ('Ana Salgado','Ana.Salgado@Urosario.Edu.Co'),
    ('Juan Carvajal','Jcarvajal@Orf.Com.Co'),
    (NULL,'Elevator.Co@Otis.Com'),
    ('Jose Ardila','Ardila.J@Pg.Com'),
    ('Roxana Martinez','Martinez.R.8@Pg.Com'),
    ('Luisa Henao','Henao.L@Pg.Com'),
    ('Luisa Henao','Luisitahenao@Gmail.Com'),
    ('José  Ravelo ','Ravelo.J@Pg.Com'),
    ('Valentina Trujillo','Trujillo.V.1@Pg.Com'),
    ('Constanza  Sanz ','Sanz.Cp@Pg.Com'),
    ('Adriana  Gonzalez ','Gonzalez.Al.2@Pg.Com'),
    ('Nelson  Albornoz Patiño','Albornoz.N@Pg.Com'),
    ('Juan Jose Gil','Gil.J.4@Pg.Com'),
    ('Melissa Laverde Gomez','Mlaverde@Argos.Com.Co'),
    ('Juliana Restrepo ','Jrestrepome@Argos.Com.Co'),
    ('Maria Angélica Ayala ','Mayalab@Argos.Com.Co'),
    ('Carolina Correa','Pmascsoluciones@Gmail.Com'),
    ('Jorge Cardenas','Directorcomercial@Pagosinteligentes.Com'),
    (NULL,'Luz.Alarcon@Panpaya.Com.Co'),
    ('Armando Rey Gonzalez ','Armandorey13@Hotmail.Com'),
    ('Armando De Jesus Rey Gonzalez','Rey.Armando@Co.Panasonic.Com'),
    ('Gustavo Montero ','Montero.Gustavo@Co.Panasonic.Com.Co'),
    ('Gonzalo Antes Figueroa','Antes.Gonzalo@Pa.Panasonic.Com'),
    ('Jean Carlos Carpintero Barandica ','Jean.Carpintero@Papelesnacionales.Com'),
    ('Juliana Villegas ','Juliana.Villegas@Papelesnacionales.Com'),
    ('Laura Marãƒâ­A Guzmãƒâ¡N Moya ','Laura.Guzman@Papelesnacionales.Com'),
    ('Wendy Viviana Burgos Martinez ','Wendy.Burgos@Papelesnacionales.Com'),
    ('Yudy Leon','Yudy.Leon@Papelesnacionales.Com'),
    ('Luisa Fernanda Diaz','Luisa.Diaz@Papelesnacionales.Com'),
    ('Jeisson Vasquez','Jeisson.Vasquez@Papelesnacionales.Com'),
    ('Silvia Pulido ','Silvia.Pulido@Papelesnacionales.Com'),
    ('Leddy Jhoanna Garcia Baez','Leddy.Garcia@Papelesnacionales.Com'),
    ('Johanna Marcela Barrera Chavez ','Johanna.Barrera@Papelesnacionales.Com'),
    ('Margarita Castrillon','Margarita.Castrillon@Papelesnacionales.Com'),
    ('Maria Alejandra Agredo','Maria.Agredo@Papelesnacionales.Com'),
    ('Hans Rosenkranz','Hans.Rosenkranz@Papelesnacionales.Com'),
    ('Enrique Cardozo','Enrique.Cardozo@Papelesnacionales.Com'),
    ('Luis Jaimes','Luis.Jaimes@Papelesnacionales.Com'),
    ('Yolanda Lopez','Marben241@Hotmail.Com'),
    ('Juan Pablo Bolivar','Juan.Nose@Nose.Com'),
    (NULL,'Lina_Palau@Parmalat.Com.Co'),
    (NULL,'Yolima_Pinto@Parmalat.Com.Co'),
    (NULL,'Paula_Solorzano@Parmalat.Com.Co'),
    (NULL,'Andrea_Paez@Parmalat.Com.Co'),
    ('Adriana Gutierrez','Adrianagutierrezrojas@Hotmail.Com'),
    ('Juan Velasquez','Juan.Pvelasquez@Wom.Co'),
    ('Diana Cortes','Diana.Cortes@Payulatam.Com'),
    ('Liliana Andrea  Romero Ramos','Liliana.Romero@Pepeganga.Com'),
    (NULL,'Andres.Gomez@Pepsico.Com'),
    (NULL,'Victoria.Garcia@Pepsico.Com'),
    (NULL,'Mariapaula.Mendezmoller@Pepsico.Com'),
    ('Lourdes Arisbeth López Arias','Lourdesarisbeth.Lopezarias@Pepsico.Com'),
    ('Carolina Monticelli ','Carolina.Monticelli@Pepsico.Com'),
    ('Claudia Pinto Muñoz','Claudia.Pinto@Pepsico.Com'),
    ('Gerardo Martin Ruzo Lenzi','Gerardomartin.Ruzolenzi@Pepsico.Com'),
    ('María Peñuela ','Maria.Penuelajaramillo@Pepsico.Com'),
    ('Matias Meynet Maechtig ','Matiasjoaquin.Meynetmaechtig@Pepsico.Com'),
    ('Natalia De La Cruz ','Natalia.Delacruz@Pepsico.Com'),
    ('Carlos Alberto Beltran ','Carlosalberto.Beltran@Pepsico.Com'),
    ('Juan Camilo Palacio ','Juancamilo.Palaciomendez@Pepsico.Com'),
    ('Disanzo Nadia Fernandez ','Nadia.Fernandez@Pepsico.Com'),
    ('Carlos Miranda ','Carlos.Mirandasoriano@Pepsico.Com'),
    ('Ana Carolina Fargetti ','Ana.Fargetti@Pepsico.Com'),
    ('Roberto Pedraza ','Rpedrazapinillos@Gmail.Com'),
    ('Catalina Rodríguez','Catalina.Rodriguezacosta@Pepsico.Com'),
    ('Paola Blanco ','Paolaeugenia.Blancolloreda@Gmail.Com'),
    ('Samantha Gómez Piña González','Samantha.Gomezpinagonzalez@Pepsico.Com'),
    ('Agustin Santiago Ordoñez ','Agustin.Santiagoordonez@Pepsico.Com'),
    (NULL,'Joseluis.Silva@Pepsico.Com'),
    (NULL,'Luisalejandro.Zarate@Pepsico.Com'),
    ('Laura Juliana Gomez Salas','Laura.Gomezs@Pepsico.Com'),
    ('Jimena Garrido ','Jimena.Garrido@Pepsico.Com'),
    (NULL,'Angelica.Alvarado@Pepsico.Com'),
    (NULL,'Josemauriciocasas@Gmail.Com'),
    (NULL,'Thumano@Pesquerajaramillo.Com'),
    (NULL,'Juan.Garcia@Pesquerajaramillo.Com'),
    ('Andres  Torres ','Andres.Torres@Pfizer.Com'),
    ('Daniela Alejandra Monroy Roa','Dalejandramonroy@Hotmail.Com'),
    ('Diego Gonzalez Montaña ','Diegoernesto.Gonzalez@Pfizer.Com'),
    ('Diego Fernando Garcia ','Diegofernando.Garcia@Pfizer.Com'),
    (NULL,'Comprascolombia@Pfizer.Com'),
    ('Yolanda  Gonzalez Barreto','Yolanda.Gonzalez@Pfizer.Com'),
    ('Eliana  Roa Parra','Elianaroaparra@Gmail.Com'),
    ('Paul Yepez','Paul.Yepez@Philips.Com'),
    (NULL,'Jackeline.Borbon@Philips.Com'),
    ('Maria Alejandra Maldonado ','Maria.Maldonado@Pmi.Com'),
    ('Santiago Uribe Tafurt','Santiago.Uribe@Pmi.Com'),
    ('Ingrid Johana Bautista Parra','Ingrid.Bautista@Pmi.Com'),
    ('Maria Gonzalez ','Maria.Gonzalez@Pmi.Com'),
    (NULL,'Johanna.Cubillos@Pintuco.Com'),
    (NULL,'Juliana.Correa@Pintuco.Com');
INSERT INTO Base_Consolidada_Asistentes_Catman VALUES
    ('Andrés Betancur Álvarez','Andres.Betancur@Pintuco.Com'),
    (NULL,'Alejandra.Javela@Pintuco.Com'),
    ('Adriana Falla Ll.','Adriana.Falla@Pintuco.Com'),
    ('Adela Aguirre','Adela.Aguirre@Pintuco.Com'),
    ('Adriana  Cabrices Herrera','Acabrices@Pisa.Com.Mx'),
    ('Carmen Sofia Uzcategui Colon','Csuzcateguic2@Gmail.Com'),
    ('Laura  Reina ','Laura.Reina.N@Gmail.Com'),
    (NULL,'Plasdecol@Grupophoenix.Com'),
    (NULL,'Mercadeo.Asistente@Rimax.Com.Co'),
    (NULL,'Mercadeo.Muebles@Rimax.Com.Co'),
    (NULL,' Gerente.General@Rimax.Com.Co'),
    ('Gabriel Domãƒâ­Nguez Silva','Gabriel06Silva@Yahoo.Es'),
    ('Gabriel Dom√≠Nguez Silva','Jgdominguezs@Alqueria.Com.Co'),
    (NULL,'Directorcs@Pollo.Fiesta.Com ; Mercadeo@Pollo-Fiesta.Com'),
    (NULL,'Asistentemercadeo@Savicol.Com.Co ; Asistentemercadeo2@Savicol.Com.Co'),
    (NULL,'Angelarodriguez@Savicol.Com.Co'),
    (NULL,'Rodrigogranados@Savicol.Com.Co'),
    (NULL,'Savicol@Savicol.Com.Co'),
    ('Maria Peña','Maria.Pena@Positiva.Gov.Vo'),
    ('Maria Camila Baez','Mariac.Baez@Positiva.Gov.Co'),
    ('Margarita Restrepo','Mmrestrepo@Postobon.Com.Co'),
    ('Emilio Yepes','Eyepesl@Postobon.Com.Co'),
    ('Andrés Felipe Gil Betancourt','Afgil@Postobon.Com.Co'),
    ('Carlos Andrés Huertas Cardona','Chuertas@Postobon.Com.Co'),
    ('Eliana Berrio Duque','Eberrio@Postobon.Com.Co'),
    ('Manuela Rubiano ','Mrubiano@Postobon.Com.Co'),
    ('Natalia Henao Idárraga','Nhenaoi@Postobon.Com.Co'),
    ('Felipe Bautista','Nfbautista@Gaslux.Com.Co'),
    ('Santiago Ferrer','Pracscm@Postobon.Com.Co'),
    ('Luisa García','Lfgarcia@Postobon.Com.Co'),
    ('Manuela Trujillo','Mtrujillo@Postobon.Com.Co'),
    ('Andrés Felipe Gil Betancourt','Oscar.Mora@Simonizco.Com'),
    ('Juan Pablo Arango Alvarez','Jparango@Postobon.Com.Co'),
    ('Marcela Echeverri Agudelo','Mecheverria@Postobon.Com.Co'),
    ('Paola Tapias','Ptapias@Postobon.Com.Co'),
    ('Tatiana Perdomo','Lperdomo@Postobon.Com.Co'),
    ('Clara Ospina Ramírez','Cospina@Postobon.Com.Co'),
    (NULL,'Pbeltran@Gaslux.Com.Co '),
    (NULL,'Anaranjo@Postobon.Com.Co '),
    (NULL,'Jolarte@Gaslux.Com.Co '),
    (NULL,'Aocampo@Postobon.Com.Co'),
    (NULL,'Mguerrero@Gaslux.Com.Co'),
    (NULL,'Jgomez@Gaslux.Com.Co'),
    ('Laura Ochoa ','Laura.Ochoal@Prebel.Com.Co'),
    ('Sara Mejia Maya','Sara.Mejia@Prebel.Com.Co'),
    ('Paola Toro ','Paola.Toro@Prebel.Com.Co'),
    ('Catalina Gil Bustamante','Catalina.Gil@Prebel.Com.Co'),
    (NULL,'Prac.Formaciond@Prebel.Com.Co'),
    ('Angelica Rojas','Angelica.Rojas@Prebel.Com.Co'),
    ('Mariana Vasquez','Mariana.Vasquez@Prebel.Com.Co'),
    ('Carolina Muñoz','Carolina.Munoz@Prebel.Com.Co'),
    ('Cristina Ramirez','Maria.Ramirezgo@Prebel.Com.Co'),
    ('Catalina Restrepo Yepes','Catalina.Restrepoy@Prebel.Com.Co'),
    ('Juliana Bernal Correa','Juliana.Bernal@Prebel.Com.Co'),
    ('Isabel Ferrer','Isabel.Ferrer@Prebel.Com.Co'),
    ('Lina Tamayo','Lina.Tamayo@Prebel.Com.Co'),
    ('Alvaro Martínez 2','Alvaro.Martinez@Prebel.Com.Co'),
    (NULL,'Dardila@Frayco.Com.Co'),
    (NULL,'Luzdary.Lagos@Holdingvml.Com'),
    ('Teresa Paez','Ventas@Helisa.Com'),
    (NULL,'Ana.Salas@Juanvaldezcafe.Com'),
    ('Alejandra Diaz Cano','Mayra.Diaz@Juanvaldezcafe.Com'),
    ('Olga M. Alfonso Sánchez','Olga.Alfonso@Juanvaldezcafe.Com'),
    ('Diana Rojas','Dirojas@Procaps.Com.Co'),
    ('Michelle  Herrera Garcia','Mherrera@Procaps.Com.Co'),
    ('Camilo Ricardo Suarez Ochoa','Csuarez@Procaps.Com.Co'),
    ('Maria Antonia Muñoz Londoño','Munoz.M.10@Pg.Com'),
    (NULL,'Solo Reciben En Físico.'),
    ('Estefany Torres','Torres.E@Pg.Com'),
    ('Maria Paula Ospina Rubiano ','Ospina.M.1@Pg.Com'),
    (NULL,'Farestrepo@Pastasdoria.Com'),
    (NULL,'Tparra@Pastasdoria.Com'),
    ('Alicia  Garcia','Gerenciamercadeo@Cosmeticosanamaria.Com'),
    ('Alicia Garcia',' Gerenciamercadeo@Cosmeticosanamaria.Com'),
    (NULL,'Aholguin@Alqueria.Com.Co'),
    ('Jeymy Alexandra Sosa Camargo ','Jeimysc@Grupofamilia.Com'),
    (NULL,'Federicojj@Familia.Com.Co'),
    (NULL,'Notificaciones@Familia.Com.Co'),
    (NULL,'Isabelpg@Familia.Com.Co'),
    (NULL,'Mariaub@Familia.Com.Co'),
    (NULL,'Obello@Alqueria.Com.Co'),
    (NULL,'Ngil@Alqueria.Com.Co'),
    (NULL,'Ccaicedo@Alqueria.Com.Co'),
    (NULL,'Juribe@Alqueria.Com.Co'),
    (NULL,'Ngonzalezg@Alqueria.Com.Co'),
    (NULL,'Tvivas@Alqueria.Com.Co'),
    (NULL,'Gvelasco@Alqueria.Com.Co'),
    (NULL,'Epfeifer@Alqueria.Com.Co'),
    (NULL,'Sbaena@Alqueria.Com.Co'),
    (NULL,'Lgarcia@Alqueria.Com.Co'),
    (NULL,'Auribe@Alqueria.Com.Co'),
    (NULL,'Lmunoz@Alqueria.Com.Co'),
    (NULL,'Faricapa@Alqueria.Com.Co'),
    (NULL,'Avasquez@Alqueria.Com.Co'),
    (NULL,'Alqueria@Alqueria.Com.Co'),
    ('Daniela Serrano','Daniela.Serrano@Ramo.Com.Co'),
    ('Juan Carlos Bustos Pachon','Aprendiztrade@Ramo.Com.Co'),
    ('Jennifer Beltran','Jenifer.Beltran@Ramo.Com.Co'),
    ('Alvaro Osorio','Aosorio@Ramo.Com.Co'),
    ('Diego Muñoz','Diego.Munoz@Ramo.Com.Co'),
    (NULL,'Cluders@Ramo.Com.Co'),
    (NULL,'Hquintero@Ramo.Com.Co'),
    ('Olga Lucia Medellin Prieto','Olga.Medellin@Ramo.Com.Co'),
    ('Nataly Gooding','Nataly.Gooding@Ramo.Com.Co'),
    (NULL,'Alejandroj@Yupi.Com.Co'),
    ('Daniel Cuellar Montes ','Dcuellar91.Dc@Gmail.Com'),
    ('Jose Pablo Saãƒâ±Udo Escobar','Directorventas@Promoventas.Net'),
    ('Jorge Paúl Segovia Monge','Jpsegoviam@Pronaca.Com'),
    ('Jaime Saavedra ','Jsaavedra@Pronaca.Com'),
    ('Luz Velasquez','Luzesneida@Yahoo.Com'),
    ('Juan Restrepo','Jrestrepo@Proquident.Com.Co'),
    ('Olga Blanco','Jefemercadeo@Proquident.Com.Co'),
    ('Alvaro Garces','Agarces@Proquinal.Com'),
    ('Johana Gomez ','Johana.Gomez.Pacheco@Hotmail.Com'),
    ('Adriana Garcia Bravo','Agarcia@Publik.Co'),
    ('Adrés Mauricio Llano Franco','M.Llano@Publik.Co'),
    ('Laura Giraldo Sarabia','Laura.Giraldo@Publik.Co'),
    ('Jackeline Montoya Galeano','Jackymontoya@Publia.Co'),
    ('Ricardo Castellanos Segura','Ricardo.Castellanos@Publimetro.Co'),
    ('Mauricio Ramãƒâ­Rez ','Mauricio.Ramirez@Puntoscolombia.Com'),
    ('Quevin Johan Quitian Fajardo','Quevinjoqui@Gmail.Com'),
    ('Diego Barreto','Dbarreto@Qbco.Biz'),
    (NULL,'Dsanchezp@Quala.Com.Co'),
    (NULL,'Mailto:Dsanchezp@Quala.Com.Co'),
    ('Juan David Cadavis','Mercadeo@Quala.Com'),
    ('Sara Lujan','Slujan@Quala.Com.Co'),
    ('Andrea Gómez Guerrero','Andrea.Gomez.Guerrero3192@Gmail.Com'),
    ('María Peñuela','Mpenuela@Quala.Com.Co'),
    ('Laura Buritica','Lburitica@Quala.Com.Co'),
    ('Camilo Parra','Cparram@Quala.Com.Co'),
    ('John Freddy Suarez Lasso','Jsuarezl@Quala.Com.Co'),
    ('Ana Maria Vargas ','Avargasn@Quala.Com.Co'),
    (NULL,'Ngonzalezb@Quala.Com.Co'),
    (NULL,'Propuestaquala@Yahoo.Es'),
    (NULL,'Quala@Quala.Com.Co'),
    ('Victor Manuel Castaño Gonzalez','Vcastano@Quala.Com.Co'),
    ('Stefanny Leguizamon','J.Fernandezreyes@Quun.Com'),
    ('Sandra Bautista','Samibaru_Ramo@Hotmail.Com'),
    ('Sandra Bautista','Sbautist@Ramo.Com.Co'),
    ('Daniela Osorio Ocampo','Tatiana.Aponte@Ramo.Com.Co'),
    ('Camila Cortes','Maria.Cortes@Ramo.Com.Co'),
    ('Johana Lizeth Quemba Manrique','Johana.Quemba@Ramo.Com.Co'),
    ('Luisa Fernanda Munar','Luisa.Munar@Ramo.Com.Co'),
    ('Alvaro Jose Osorio Cadavid','Aosorio@Ramo.Com,Co'),
    ('Bryan Nicolas Vidal Ruiz','Jaime.Sabogal@Ramo.Com.Co'),
    ('Julian David Hernandez Baez','Julian.Hernandez@Ramo.Com.Co'),
    ('Natalia Roa','Yised.Roa@Ramo.Com.Co'),
    ('Daniel  Muñoz ','Comercial@Rawmco.Com.Co'),
    ('Tomás Vanegas Murillo','Mercadeoventas@Rawmco.Com.Co'),
    ('Sara Ordoñez','Sara.Ordonez@Rb.Com'),
    (NULL,'Carlos.Restrepo@Rb.Com'),
    ('Santiago  Naranjo ','Santiago.Naranjo@Rb.Com'),
    ('Lina  Portillo ','Lina.Portillo@Rb.Com'),
    ('Giovanny Andrãƒâ©S Montoya Andrade ','Gio_Montoya1804@Hotmail.Com'),
    ('Diana Gaitan','Diana.Gaitan@Rb.Com'),
    ('Bryan Campuzano','Bryan.Campuzano@Rb.Com'),
    ('Juan Sebastian Rodriguez ','Juansebastian.Rodriguez@Rb.Com'),
    ('David Valencia Vida','David.Valencia@Rb.Com'),
    ('Maria Paula Gaviria Gonzalez','Maria.Gaviriagonzalez@Rb.Com'),
    ('Jose Francisco Semaan','Francisco.Semaan@Rb.Com'),
    ('Juan Sebastian Montoya','Juan.Montoya@Rb.Com'),
    ('Vivian Carolina Diaz Sanchez','Vivian.Diaz@Rb.Com'),
    (NULL,'Marieadriana.Cruz@Rb.Com'),
    ('Jose Luis Torres Bustamante','Jltorres.Rc@Gmail.Com'),
    (NULL,'Ximena.Hacelas@Co.Redbull.Com'),
    (NULL,'Daniel.Rozo@Co.Redbull.Com'),
    ('Reinaldo Bolivar Amaya','Rbolivar@Maravilla.Com.Co'),
    ('Gonzalo E Idarraga Ospina','Gerencia@Droguerias9192.Com.Co'),
    ('Oscar Torres','Otorres@Rich.Com'),
    (NULL,'C.Vargas@Riopaila-Castilla.Com'),
    (NULL,'Imptosriocas@Riopaila-Castilla.Com'),
    ('Sebastian  Taboada Diaz','Sebastian.Taboada@Roche.Com'),
    (NULL,'Monica.Suarez@Ronda.Com.Co'),
    ('Anabella Cadena','Anabella.Cadena@Royalcanin.Com'),
    (NULL,'Amromero@Scj.Com'),
    ('Andrés Beltrán ','Andres.Beltran@Saint-Gobain.Com'),
    (NULL,'Nirzabarreto@Salitreplaza.Com.Co'),
    ('Laura Yasy Fernandez Anzola','Crm@Salitreplaza.Com.Co'),
    ('Clara Ines Robledo Velez','Clararobledo@Salitreplaza.Com.Co'),
    (NULL,'Claudiacamacho@Salitreplaza.Com.Co'),
    ('Janeth Constanza Morales A.','Constanzamorales@Salitreplaza.Com.Co'),
    ('Rosine Dallos Jabbour','Rosine.Dallos@Samsonite.Com'),
    ('Ricardo Torres Richoux','Torres.Richoux@Gmail.Com'),
    (NULL,'Jose.Pinto@Samsung.Com'),
    ('Soany  Orrego Carvajal','Soany.Orrego@Bussie.Com.Co'),
    ('Luis Eduardo Avila Cruz','Luis.Avila@Bussie.Com.Co'),
    (NULL,'Paola.Alfonso@Sanofi.Com'),
    (NULL,'Carlos.Ramirez@Sanofi.Com'),
    ('Juan Pablo Carvajal Rincón','Juanpablo.Carvajal@Sanofi.Com'),
    (NULL,'Felipe.Moreno@Sanofi.Com'),
    (NULL,'Paula.Trivino@Sanofi.Com'),
    (NULL,'Jaime.Botero@Sanofi.Com'),
    (NULL,'Fabioeduardo.Mejia@Sanofi.Com'),
    ('Viviana Apolinar','Viviana.Apolinar@Sanofi.Com'),
    (NULL,'Mariana.Giraldo@Sanofi.Com'),
    (NULL,'Gustavo.Diazvargas@Sanofi.Com'),
    (NULL,'Marcela.Sernazuluaga@Sanofi.Com'),
    (NULL,'Pierre.Lacaze@Sanofi.Com'),
    (NULL,'Andresfelipe.Ruiz@Sanofi.Com'),
    (NULL,'Herman.Patino@Sanofi.Com'),
    (NULL,'Paulo.Hernandez@Sanofi.Com'),
    (NULL,'Sandrapatricia.Ruiz@Sanofi.Com'),
    ('Juan Carlos Morales Vasquez','Juan.Morales2@Sanofi.Com'),
    ('Carol-Ann  Stewart ','Carol-Ann.Stewart@Sanofi.Com'),
    (NULL,'Mauricio.Oliveira@Sanofi.Com'),
    (NULL,'Gustavo.Urrea@Sanofi.Com'),
    ('Natalia  Villate ','Natalia.Villate@Sanofi.Com'),
    (NULL,'Mauricio.Botero@Sanofi.Com'),
    (NULL,'Consuelo.Alvarado@Sanofi.Com'),
    (NULL,'Marcela.Bocanegra@Sanofi.Com'),
    (NULL,'Mariacarolina.Gomez@Sanofi.Com'),
    (NULL,'Camilo.Sanchez@Sanofi.Com'),
    (NULL,'Luisfernando.Castro@Sanofi.Com'),
    (NULL,'Ana.Velasquez@Sanofi.Com'),
    (NULL,'Anamaria.Supelano@Sanofi.Com'),
    (NULL,'Andrea.Correajaramillo@Sanofi.Com'),
    (NULL,'Andres.Sarkis@Sanofi.Com'),
    (NULL,'Andres.Zarate@Sanofi.Com'),
    (NULL,'Carlos.Mejia2@Sanofi.Com'),
    (NULL,'Dianacarolina.Lopez@Sanofi.Com'),
    (NULL,'Dianapatricia.Rodriguez@Sanofi.Com'),
    (NULL,'Juan.Cardenas@Sanofi.Com'),
    (NULL,'Liliana.Uribe@Sanofi.Com'),
    (NULL,'Mariaconsuelo.Prieto@Sanofi.Com'),
    (NULL,'Jorgenel.Rojas@Sanofi.Com'),
    ('Patricia  Navas ','Patricia.Navas@Sanofi.Com'),
    (NULL,'Luis.Cordoba@Sanofi.Com'),
    (NULL,'Luz.Basto@Sanofi.Com'),
    (NULL,'Diana.Angarita@Sanofi.Com'),
    (NULL,'Juanmanuel.Pena@Sanofi.Com'),
    (NULL,'Liliana.Feghali@Sanofi.Com'),
    ('Alexandra  Pardo Londoño','Alexandra.Pardo2@Sanofi.Com'),
    (NULL,'Alberto.Nieto@Sanofi.Com'),
    (NULL,'Alexander.Sosa@Sanofi.Com'),
    (NULL,'Anamaria.Fernandezhernandez@Sanofi.Com'),
    (NULL,'Claudia.Muette@Sanofi.Com'),
    (NULL,'Hugoalexander.Sanchez@Sanofi.Com'),
    (NULL,'Mariacatalina.Villegas@Sanofi.Com'),
    (NULL,'Samira.Macias@Sanofi.Com'),
    (NULL,'Cristina.Jimenez@Sanofi.Com'),
    ('Carlos Hernan Llanos Isaza','Carlos.Llanos@Sanofi.Com'),
    ('Andrea  Neira ','Andrea.Neira@Sanofi.Com'),
    ('Diana Patricia Garcia Puentes','Diana.Garciapuentes@Sanofi.Com'),
    (NULL,'Andresfelipe.Higuera@Sanofi.Com'),
    (NULL,'Ivonne.Bolanos@Sanofi.Com'),
    (NULL,'Yanindone.Rodriguez@Sanofi.Com'),
    (NULL,'Mauricioalejandro.Hernandez@Sanofi.Com'),
    (NULL,'Claudia.Ospina@Sanofipasteur.Com'),
    (NULL,'Josefernando.Martinez@Sanofipasteur.Com'),
    (NULL,'Marcela.Jaramillo@Sanofipasteur.Com');
INSERT INTO Base_Consolidada_Asistentes_Catman VALUES
    (NULL,'Maria.Jimenez@Sanofipasteur.Com'),
    (NULL,'Sandra.Ibagon@Sanofi.Com'),
    (NULL,'Sebastian.Gomez@Sanofi.Com'),
    (NULL,'Mariapiedad.Cortes@Sanofi.Com '),
    ('Juan Ignacio Pérez ','Juanignacio.Perez@Sanofi.Com'),
    (NULL,'Andres.Cordoba@Sanofi.Com'),
    (NULL,'Eliana.Zambrano@Sanofi.Com'),
    ('Daniela  Guevara ','Ldaniela_2@Hotmail.Com'),
    ('Alexander  Barrios ','Alexander.Barrios@Sanofi.Com'),
    ('Juan Sebastian Perez Angel','Jusepe_63@Hotmail.Com'),
    ('Jairo Alfonso Ceballos Polanco','Jairo.Ceballos@Sanofi.Com'),
    ('Niño Manrique','Joalasker@Gmail.Com'),
    ('Luz Stella Parra Dominguez','Luz.Parra@Co.Lactalis.Com'),
    ('Marcela  Andrade ','Marcela.Andrade@Co.Lactalis.Com'),
    (NULL,'Info.Colombia@Sarens.Com'),
    (NULL,'Fernandogil@Savicol.Com.Co'),
    ('Cristhiam Suarez','Csuarez@Scj.Com'),
    ('Diana Baron','Dbaron@Scj.Com'),
    ('Camilo Forero Franky','Cforero@Scj.Com'),
    ('Jennie Carolina Elinan López','Jelinan@Scandinavia.Com.Co'),
    ('Claudio Ferrari Ferrando','Cferrari@Scandinavia.Com.Co'),
    ('Juan Carlos Bernal Parra','Cbernal@Scandinavia.Com.Co'),
    ('Rossmary Salazar','Rsalazar@Scandinavia.Com.Com'),
    ('Maria De Los Angeles Nivia','Mnivia@Scandinavia.Com.Co'),
    ('Raul Reyes Moreno','Rreyes@Scandinavia.Com.Co'),
    ('Catharina Lüders','Cluders@Scandinavia.Com.Co'),
    ('Carlos Enrique Vallejo Fernandez','Carlosvallejo@Seacompetitivo.Com'),
    ('Carlos Mario Sierra I','Carlossierra@Seacompetitivo.Com'),
    ('Liliana Pacheco','Liliana.Pacheco@Vancamps.Com.Co'),
    ('Carlos Siado','Casiado@Yahoo.Com'),
    ('Jennifer Quintero','Jenniferq@Sempertex.Com'),
    ('Marcela Guillermety','Marcelag@Sempertex.Com'),
    ('Javier Huertas','Jhuertasmojica@Gmail.Com'),
    ('Andrea Carolina Devia','Multicanalcorporativo.Dg@Servientrega.Com'),
    ('María Clara Martínez','Maria.Martinez@Sherpa.Com.Co'),
    ('Amalia Arango ','Amalia.Arango@Sherpa.Com.Co'),
    ('Gina Paola Rodriguez Gantiva','Gprodriguez@Sicmafarma.Com'),
    ('Fabian Ruiz ','Fabian.Ruiz@Siemens.Com'),
    (NULL,'Webmaster.Ranr@Siemens.Com'),
    ('Adriana Araya','Aaraya@Sigma-Alimentos.Co.Cr'),
    ('Alberto Carrillo Gutierrez','Alberto.Carrillo@Signumresearch.Com'),
    (NULL,'Fernanda.Salamanca@Sigra.Com'),
    ('Pedro Jesus Perez','Pedro.Perez@Sigra.Com'),
    ('Yeny Neva Bohorquez','Yeny.Neva@Sigra.Com'),
    (NULL,'Diana.Baron@Sigra.Com ; Servicio.Maestro@Sigra.Com '),
    (NULL,'Juliana.Chaparro@Sigra.Com'),
    ('Maritza Velasquez','Mary.Velasquez@Sigra.Com'),
    ('Yeny Neva Bohãƒâ³Rquez','Yenyneva79@Gmail.Com'),
    (NULL,'Calvarez@Tecnifabrica.Com'),
    (NULL,'Acastrillon@Titangroup.Com.Co ; Acastrillon@Tecnifabrica.Com'),
    ('Juan Carlos Hernandez Canal','Jchernandez@Siscolfarma.Com'),
    ('Julian Moncada Restrepo','Jmoncada@Isis-Pharma.Com'),
    ('Juan Carlos Hernandez Canal','Jchhernandez@Siscolfarma.Com'),
    (NULL,'Claudia.Devia@Smurfitkappa.Com.Co'),
    ('Vannesa Hatty Benavides','Vanessa.Hatty@Smurfitkappa.Com.Co'),
    ('Diana Milena García Cobos','Diana.Garcia@Smurfitkappa.Com.Co'),
    ('Stefano Manzi Puello','Stefano.Manzi@Smurfitkappa.Com.Co'),
    ('Ana Maria Montealegre','Amontealegre@Homecenter.Co'),
    (NULL,'Abeltrang@Homecenter.Com.Co'),
    (NULL,'Servicioalcliente@Homecenter.Com.Co'),
    (NULL,'Emquintana@Homecenter.Com.Co'),
    (NULL,'Gdiazb@Homecenter.Com.Co'),
    (NULL,'Dlasso@Homecenter.Com.Co'),
    ('Fabian Sanchez R','Fsanchezr@Homecenter.Co'),
    ('Freddy Alfonso Garzon Cortes','Fgarzonc@Homecenter.Co'),
    ('Mauricio Hoyos','Mhoyos@Solucionesanaliticas.Co'),
    ('Ana Maria Castaño Tamayo','Amcastanot@Solla.Com'),
    ('Ana Carolina Palacio','Acpalacio@Solla.Com'),
    ('Maria Paulina Jimenez','Mpjimenez@Solla.Com'),
    ('Alejandra Mendez','Amendez@Solla.Com'),
    (NULL,'Dalia.Gutierrez@Ghlhoteles.Com'),
    (NULL,'Norma.Toca@Sophossolutions.Com'),
    ('Ana Gomez','Ana.Gomez@La.Spectrumbrands.Com'),
    ('Laura Milena Caballero Avila','Carlos.Contreras@Fahorro-Ext-Com.Mx'),
    ('Sandra Lorena Delgado','Lorena.Delgado@La.Spectrumbrands.Com'),
    ('Maria Andrea Santana ','Andrea2901@Hotmail.Com'),
    ('Marcela Jurado ','Marcela.Jurado@La.Spectrumbrands.Com'),
    ('Johana Cardenas','Johana.Cardenas@Steren.Com.Co'),
    ('Sergio Gurrola Trujillo','Sergio.Gurrola@Super.Com.Co'),
    ('Tatiana Garcãƒâ­A ','Tatis.Garcia@Gmail.Com'),
    ('Jack','Mercadeo.Supercool@Gmail.Com'),
    ('Sandra Moreno','Sandra.Moreno@Lgc.Com.Co'),
    (NULL,'Servipro@La14.Com ; Sistemas@La14.Com '),
    (NULL,'Rdorado@Olimpica.Com.Co'),
    ('Javier Cohenar','Javier@Suplai.App'),
    ('Sol Caicedo','Sol.Caicedo@Susanita.Com'),
    ('Maryam Amatai Liberman','Maryana@Sutex.Com'),
    ('Filipe Augusto Teixeira ','Filipe.Teixeira@Takeda.Com'),
    ('Jorge  Arango ','Jorge.Arango@Takeda.Com'),
    ('Reinaldo Andres Soto Soto','Reinaldo.Soto@Shire.Com'),
    ('Ferney  Rincon ','Luis.Rincon@Takeda.Com'),
    ('Luisa  Romero ','Luisa.Romero@Takeda.Com'),
    (NULL,'Ml@Tarazonagroup.Com'),
    ('Maria Alejandra Quintana Romero','Maria.Quintana@Team.Co'),
    ('Natalia Jimenez Ortiz','Natalia.Jimenez@Team.Co'),
    ('Herman Adolfo Castellanos Arango','Hcastellanos@Team.Co'),
    ('Andrea Rebolledo Ujueta','Andrea.Rebolledo@Team.Co'),
    ('Luis Alberto Botero','Lbotero@Team.Co'),
    (NULL,'Mlopera@Teamfoods.Com'),
    (NULL,'Mgiraldo@Teamfoods.Com'),
    (NULL,'Davidconstain@Teamfoods.Com'),
    (NULL,'Jmcallister@Teamfoods.Com'),
    (NULL,'Diegomez@Teamfoods.Com'),
    ('Nedsy Lian Porras Ortiz','Nporras@Tecnofarma.Com.Co'),
    ('Mónica Esperanza Pulido García','Mpulido@Tecnofarma.Com.Co'),
    ('Ricardo  Castillo Gil','Rcastillo@Tecnofarma.Com.Co'),
    ('Marlon  Sterling ','Msterling@Tecnoquimicas.Com'),
    ('Pablo  Orejuela ','Prorejuela@Tecnoquimicas.Com'),
    ('Johan Jimenez','Jjjimenez@Tecnoquimicas.Com'),
    ('Milena Higuera','Mhiguera@Tecnoquimicas.Com'),
    ('Andres  Marin ','Ammarin@Tecnoquimicas.Com'),
    ('Piedad  Benavides ','Rpbenavides@Tecnoquimicas.Com'),
    ('Maria Del Pilar Rizo Arango','Mprizo@Tecnoquimicas.Com'),
    ('Ricardo  Correa ','Rcorrea@Tecnoquimicas.Com'),
    ('Silvia Lorena Avila Rojas','Slavila@Tecnoquimicas.Com'),
    ('Juliana  Herrera ','Jherrera@Tecnoquimicas.Com'),
    ('Jaime  Saenz ','Jisaenz@Tecnoquimicas.Com'),
    ('Carolina Semaan Lince','Csemaan@Tecnoquimicas.Com'),
    (NULL,'Edgart@Teleaccion.Com'),
    (NULL,'Carlosospina@Telefonica.Com'),
    (NULL,'John.Morales.N@Claro.Com.Co'),
    (NULL,'William.Giraldo@Claro.Com.Co'),
    ('Guillermo Reyes','Trade@Tequilapapelpicado.Com'),
    ('Jose Raul Paramo','Jparamo@Terranum.Com'),
    ('Alexandra Parra','Yparra@Angeltex.Com.Co'),
    ('Luis Daniel Mancipe Lãƒâ³Pez','Gerenciamarketing@Thecoffeehub.Co'),
    ('Julio Ibanez','Chairman@Hispanicretailchamber.Org'),
    ('Daniel Novoa','Business.Director@Hispanicretailchamber.Org'),
    (NULL,'Mvelez@Theone.Com.Co'),
    ('Martin Vom Stein','Martin.Vom.Stein@Theshopsumerinstitute.Com'),
    ('Paola Gómez Pico','Tigo.Com.Co'),
    (NULL,'Servicioalcliente@Totto.Com'),
    ('Astrid Farieta','Emilia.Ramirez@Hotmail.Com'),
    ('Harold Jaramillo','Hajaramillo@Tecnoquimicas.Com'),
    ('Christian  Ramirez Echave','Cramirez@Tecnoquimicas.Com'),
    (NULL,'Nicolas@Traxretail.Com'),
    ('Ana Samper Jaramillo','Ana.Samper@Trianon.Com.Co'),
    ('Diana Yepes','Coord.Tradetrg@Triguisar.Com.Co'),
    ('Santiago Restrepo Botero','Santiagorestrepo@Tronex.Com'),
    ('Back Up Carlos Londono','Carloslondono@Tronex.Com'),
    ('Santiago Mesa','Santiagomesa@Tronex.Com'),
    ('Santiago Herrera','Saherrema@Yahoo.Com'),
    ('Santiago Herrera M.','Santiago.Herrera@Tucash.Co'),
    ('Claudia Cortes','Jorge.Benavides@Mabe.Co'),
    (NULL,'Yannis@Txt.Co'),
    ('Virgilio Comas','Comas09@Hotmail.Com'),
    ('Juan Pablo Senmache','Juan.Senmache@Ab-Inbev.Com'),
    ('Yaneth Aconcha','Yaconcha@Gmail.Com'),
    ('Alexander Gomez','Alexandergomez@Unidrogas.Net.Co'),
    ('Martha Bustamante','Coordinadomicilios@Unidrogas.Net.Co'),
    ('Alexis Fernando Carvajal Prieto','Gestorinformacion@Unidrogas.Net.Co'),
    ('Max Lorduy','Maxlorduy@Gmail.Com'),
    ('Daniel Melendez','Daniels.Melendez86@Gmail.Com'),
    ('Jose Luis Espinosa Moreno','Lidernacionalventas@Unidrogas.Net.Co'),
    ('Cesar Varela  ','Cesarvarela_1990@Hotmail.Com'),
    ('Dayana Ramãƒâ­Rez  ','Dayana.Ramirez@Unilever.Com'),
    ('Charlie Marx','Krx_13_05@Hotmail.Com'),
    ('Camila Vélez Rivas ','Camila.Velez@Unilever.Com'),
    ('Javier Alfonso Parra Fajardo ','Parra.Javier47@Gmail.Com'),
    ('Maria Vieira ','Maria.Vieira@Unilever.Com'),
    ('Katerin Ramirez','Katerin.Ramirez@Unilever.Com'),
    (NULL,'Domenico.Barbato@Unilever.Com'),
    (NULL,'Santiago.Vallejo@Unilever.Com'),
    (NULL,'Juan.Castro@Unilever.Com'),
    ('Hector  Hoyos ','Hivanh@Yahoo.Com'),
    (NULL,'Racedoe@Uninorte.Edu.Co'),
    (NULL,'Alfarod@Uninorte.Edu.Co'),
    (NULL,'Gmanjarr@Uninorte.Edu.Co'),
    ('Hector Hoyos','Marketingfarmaceutico@Unbosque.Edu.Co'),
    ('Isabel Meza','Posgrados.Fae@Uexternados.Edu.Co'),
    (NULL,'Jaime.Torres1@Unisabana.Edu.Co'),
    (NULL,'Julio.Barrera@Unisabana.Edu.Co'),
    (NULL,'Mateo.Arias@Unisabana.Edu.Co'),
    (NULL,'Jose.Cordoba@Hotmail.Com'),
    (NULL,'Sandra.Bedoya@Unilibrecali.Edu.Co'),
    ('Paula Garnica','Comercial1@V2Vcolombia.Com'),
    ('Juan Felipe Vega','Jfvega@V2Vcolombia.Com'),
    ('Sofia Vargas','Svargas@V2Vcolombia.Com'),
    ('Natalia Urrego','Martketing@V2Vcolombia.Com'),
    (NULL,'Dmoya@Corona.Com.Co'),
    ('Kenneth Brito','Contacto@Evans.Com.Co'),
    ('Julian Peñalosa','Julian.Penalosa@Vancamps.Com.Co'),
    (NULL,'Mguzman@Mejiaasociados.Com'),
    ('Juan Felipe Toscano Rengifo','Pipetoscano@Gmail.Com'),
    ('Claudia Camacho','Ccamacho@Visa.Com'),
    ('Valentina Manrique','Manriqueeg23@Gmail.Co'),
    (NULL,'Yuliet.Daza@Visionymarketing.Com.Co'),
    ('Cristian Mogollón','Cristian.Mogollon@Visionymarketing.Com.Co'),
    ('Diego Ardila','Diego.Ardila@Visionymarketing.Com.Co'),
    (NULL,'Agustin.Otero@Visuallatina.Com'),
    ('René Humberto Jara','Rene.Jara@Visualsoftcolombia.Com'),
    ('Gonzalo  Maldonado Sanmiguel','Gonzamal@Hotmail.Com'),
    (NULL,'Hermann196@Gmail.Com'),
    (NULL,'Alejandro.Tovar@West-Bm.Com'),
    (NULL,'Serviciook@Whirlpool.Com'),
    ('Claudia Obando Botero','Cobando_Botero@Hotmail.Com'),
    ('Alexander Quimbaya Fernandez','Alex.Quimbayaf@Gmail.Com'),
    ('Leidy Moreno','Leydi.Moreno@Wom.Co'),
    ('David Medellin','David.Medellin@Wom.Co'),
    ('Laura Alejandra Beltran Martinez','Laura.Beltran@Wom.Co'),
    ('German Torrente','German.Torrenteact@Wom.Co'),
    ('Andrea Robles','Yuli.Robles@Wom.Co'),
    ('Katya López','Katya.Lopezv@Kantarworldpanel.Com'),
    ('Diego Suarez','Zahir1219@Hotmail.Com'),
    ('David Antonio Charris Giraldo','Dcharris@Xinetixpharma.Com'),
    (NULL,'Daniel.Guzman@Xylemiinc.Com'),
    (NULL,'Pyunes@Unique-Yanbal.Com'),
    (NULL,'Erika.Castro@Yanhaas.Com'),
    ('Marcela Gutierrez','Marcelag@Yupi.Com.Co'),
    ('Ana Bolena Muñoz','Anabm@Yupi.Com.Co'),
    ('Juan  Alvarado ','Juan.Alvarado@Zambongroup.Com'),
    ('Gerardo  Rodriguez Daza','Gerardo.Rodriguez@Zamboncolombia.Com'),
    ('Hernan  Idarraga Silva','Hernan.Idarraga@Zamboncolombia.Com'),
    ('Carolina  Roa Romero','Carolina.Roa@Zamboncolombia.Com'),
    ('Mauricio  Jiménez ','Mauricio.Jimenez@Zamboncolombia.Com'),
    ('Juan Carlos Bernal Ardila','Juancarlos.Bernal@Zamboncolombia.Com'),
    ('Ricardo  Restrepo Arias','Ricardo.Restrepo@Zambongroup.Com'),
    ('Andrea Mora','Andrea.Mora@Zebra.Com'),
    (NULL,'Cramirez@Alimentoscarnicos.Com.Co'),
    ('Omar Duran','Direccionventas@Zorba.Com.Co'),
    ('Angelica Hoyos','Ahoyos@Bogotabeercompany.Com');
